### ISSUE TITLE
Marker for printed objects | Markierung für gedruckte Objekte

### ISSUE THREAD

**Issue by Experte9** [Clon1998/mobileraker#100]
**Is your feature request related to a problem? Please describe.**
In the app I have no way to see which object I have already printed. I quickly lose track because I always upload multiple files.

In der App habe ich keine Möglichkeit zu schauen welches Objekt ich schon gedruckt habe. Ich verliere schnell die Übersicht da ich immer mehrere Dateien hochlade.

**Describe the solution you'd like**
It would be nice if there was a green check mark, the font turns green or the number of times it was printed somewhere.

Es wäre schön wenn ein grüner Haken, die Schrift grün wird oder die Anzahl wie oft es gedruckt wurde irgendwo steht.

**Describe alternatives you've considered**
Currently I always look at the Moonraker web interface to find out.

Aktuell schaue ich immer auf die Weboberfläche von Moonraker um das in Erfahrung zu bekommen.

**Additional context**
Here are a few pictures of what I mean (Moonraker and Octoprint)
Hier mal ein paar Bilder was ich meine (Moonraker und Octoprint)
![Moonraker](https://user-images.githubusercontent.com/20842528/212017697-461a6daf-b115-41cb-bf85-38990a0460bf.png)
![Octoprint](https://user-images.githubusercontent.com/20842528/212017700-5c358026-af5a-46db-b6cb-9b8cb29f1dca.png)

**Comment by Clon1998** [comment]
Hey,
that's a great idea to add sth like that directly to the file browser. Currently, you could be able to look this up by checking if a selected file shows a date or no data for the "last printed" ent

![image](https://user-images.githubusercontent.com/10357775/212125625-6908948e-ddca-4c15-b25a-7f85deee2669.png)

**Comment by AustinSchulz** [comment]
I would suggest adding the indicator as a [badge](https://m3.material.io/components/badges/overview) on top of the print preview image in the list. You can display the number of times completed, and the color be the last print's final state.

**Comment by Experte9** [comment]
![image](https://user-images.githubusercontent.com/20842528/219973824-0f8fc3be-6fd0-4cfc-a047-cb07a1345739.jpeg)
