### ISSUE TITLE
Can't Dismiss Sticky Notification (Android)

### ISSUE THREAD

**Issue by Jmoore1127** [Clon1998/mobileraker#102]
**Describe the bug**
After a successful print, I turned off my printer for the evening (and by extension the pi running klipper/moonraker). However, the sticky notification for print progress will not dismiss from my phone. Since the API is not available the app cannot connect and will not dismiss the notification. 

**To Reproduce**
1. Configure progress notifications
2. Start a print
3. Check print in app (notification displays)
4. Shutdown moonraker/print host
5. Unable to dismiss progress notification

**Expected behavior**
Notification can be manually cleared or automatically expires based on some sort of timeout.

**Desktop (please complete the following information):**
 N/A

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy S21 Ultra
 - OS: Android 12
 - Browser: chrome

**Mobileraker-Version
2.0.2-76

**Comment by Clon1998** [comment]
Due to the new notification system with 2.1.x this issue should be resolved
