### ISSUE TITLE
Unable to setup reverse proxy (Synology)

### ISSUE THREAD

**Issue by Redwish89** [Clon1998/mobileraker#105]
I use Synology and have Reverse Proxy setup with SSL (wildcard), also made the header for websocket in it through the wizard in Synology. When i want to connect to the address i made the app gives me the error "WebSocketException: Connection to [URL:0#] was not upgraded to websocket" at below the test button, although it is done in the setup on Synology.

 - Device: iPhone 14
 - iOS 16.3

**Mobileraker-Version
2.0.2-76

**Additional context**
Other applications worked before with the same setup (ie Octoprint)

**Comment by Clon1998** [comment]
Hey sorry for my late reply,
could you try the latest version available trough the beta/testflight program (https://testflight.apple.com/join/h9JwuyR0).

It should show more details in regard to the actual connection problem and offer a log viewer at the bottom of the app settings page. In case it does not work please provide me with the logs.
