### ISSUE TITLE
Reorder Cards

### ISSUE THREAD

**Issue by sloscotty** [Clon1998/mobileraker#11]
This is just a feature request.  I would like to be able to reorder the cards in the app.  For example, I could move the Webcam card up to the top if desired.  Would also keep "critical" functions off the screen at the bottom so I don't accidentally "touch" a button I didn't really want to (such as baby-stepping during a print, etc.)

**Comment by grahamgraham** [comment]
This might need to be a different request, but if we could also change the order  that the “overview” shows the printers, that would be swell.

**Comment by wieluk** [comment]
It would also be nice if hiding cards would be possible. Like hide camera.

**Comment by Clon1998** [comment]
Added in android2.7.0, ios2.7.0
