### ISSUE TITLE
Bottom tabs hard to click

### ISSUE THREAD

**Issue by mWachu** [Clon1998/mobileraker#111]
**Is your feature request related to a problem? Please describe.**

UI is great, however there is a issue with navigating between controls tabs found at the bottom. I have tested in on both of my phones and issue seems to be exact same. 

<img width="575" alt="Screenshot 2023-01-31 at 13 01 51" src="https://user-images.githubusercontent.com/77017007/215755128-4d6b314f-2723-4c7a-a76c-58b850c4403a.png">

**Describe the solution you'd like**

The tap reaction should be applied for square area around the icon rather than icon itself. 

**Describe alternatives you've considered**

N/A 
**Additional context**

Maybe paid version with customisation functions, plugin integration etc?

**Comment by Clon1998** [comment]
Hey,
I just tested it with an iPhone, an Android phone, and an Android Simulator.
On all devices, there is no need to directly hit the Icon in order to get to another page.
