### ISSUE TITLE
Add rotation to camera

### ISSUE THREAD

**Issue by SergeDubovsky** [Clon1998/mobileraker#116]
Currently, there is no support for camera rotation. Some users have cameras mounted vertically. It would be helpful to have the option to rotate 90 and 270 degrees, similar to Web UI:
![image](https://user-images.githubusercontent.com/1774209/218173760-a88bb7c2-8252-428b-8c3d-84e519825824.png)

**Comment by Clon1998** [comment]
You can rotate/flip any webcam individually.
![image](https://user-images.githubusercontent.com/10357775/218179755-e1cfccca-014d-4139-8080-5764aea2c94b.png)

**Comment by Clon1998** [comment]
> Yes, I see the Flip options, but I was asking for a rotation. There is no way to get portrait mode. The flip option does mirror image, but it doesn't rotate:
> 
> ![IMG_7756](https://user-images.githubusercontent.com/1774209/218182296-179da858-4369-4b99-a157-e6b5de51b991.PNG)
> 
> Here is the WebUI:
> 
> ![IMG_7757](https://user-images.githubusercontent.com/1774209/218182298-199882b5-cfb2-41d7-b738-f412d24ff88b.PNG)
> 
> 
> 
> 

Ohh sorry.
I've reopen the issue and will look into that once i have some more time again.

**Comment by Clon1998** [comment]
I am happy to inform you that I added this feature in the dev branch via 456d8bc.
Therefore, this will be included in the next release.

Here is a screenshot to ensure I did understand the FR correctly.


![image](https://user-images.githubusercontent.com/10357775/226105922-2eed7354-d40b-4067-b5d4-c8f5080644b0.png)
