### ISSUE TITLE
Parts Fan "Off"

### ISSUE THREAD

**Issue by sloscotty** [Clon1998/mobileraker#12]
Part cooling fan reporting "Off" when Fluidd shows 20%.  Verified parts fan is operating.

**Comment by Clon1998** [comment]
Can you verify that this only happens during printing?
I've also noticed that the Part-Fan is not updating, but only during a print.
When I change the value via Fluidd, the app correctly updates.

**Comment by sloscotty** [comment]
Yes - only while printing.  If I set the fan in Fluidd, it reflects properly in Mobileraker.  If I set the fan in Mobilraker, it reflects properly in Fluidd.
