### ISSUE TITLE
Quicker Printer Change

### ISSUE THREAD

**Issue by redlinebikeparts** [Clon1998/mobileraker#121]
Firstly the app is absolutely amazing. I have recommended it to so many people now. So thank you. 

One thing I was wondering is there a way to make changing printer easier? It would be great if I could just tap on the printer name to change over. I have multiple printers so would be nice to have the option. :) 

![image](https://user-images.githubusercontent.com/126834036/222877511-0a661749-3a97-405b-bd89-72731ace9268.jpeg)

**Comment by Clon1998** [comment]
Hey,
glad you like it.

It's a bit of a hidden feature, but you can swipe along the title on most of the pages to fastly switch between printers.
(The title you draw an arrow to)

**Comment by redlinebikeparts** [comment]
Ohhh damn that's awesome thank you for letting me know.
