### ISSUE TITLE
Cannot update via moonraker

### ISSUE THREAD

**Issue by MrLowe72** [Clon1998/mobileraker#126]
**Describe the bug**
I cannot update the program on using the update section on moonraker. 

Error : 

22:27:48 | Updating Application mobileraker...
-- | --
22:27:48 | Error updating mobileraker: 'utf-8' codec can't decode byte 0xff in position 0: invalid start byte

**To Reproduce**
1. Go to 'update manager'
2. Click on 'update'
3. Scroll down to '.mobileraker'

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Mobileraker-Version
This information can be found in Android's and IOS's App-Info.

**Additional context**

**Comment by Clon1998** [comment]
Hey,
here is the link to the solution in the companion's GitHub repo.

https://github.com/Clon1998/mobileraker_companion/issues/16#issuecomment-1434346466
