### ISSUE TITLE
Mainsail System Control

### ISSUE THREAD

**Issue by maartydeboer** [Clon1998/mobileraker#127]
I really like the app and use it via vpn to access my pi. If possible I would love to have the option to shutdown my pi via app after the print is finished (as in mainsail). 

Would love to see a page/tab that has some sort of server controls, eg. restart server, restart firmware, shutdown...

As far as implementation goes, the app could send console commands when the specific button is pushed. Like in this example: https://klipper.discourse.group/t/shutdown-command-to-the-raspberry/584/2

Thanks a lot

**Comment by Clon1998** [comment]
I am not to sure what you are trying to achieve.
Mobileraker offers both support for the Power API and the option to shutdown/restart the firmware or host system.


Just try to press the burger menu in the bottom navigation bar of the dashboard view.


![image](https://user-images.githubusercontent.com/10357775/224490390-caa46856-6972-47f5-b37d-97628687475e.png)

**Comment by Clon1998** [comment]
@maartydeboer can I close the issue or are you talking about shutting down the OS on any other way 🤔

**Comment by maartydeboer** [comment]
HEy, you can close this issue :) thanks a lot
