### ISSUE TITLE
Automatically redirect to active 3D printer from notification

### ISSUE THREAD

**Issue by DrFate09** [Clon1998/mobileraker#128]
Currently, if you have more than one printer set up in Mobileraker and tap on a print progress notification, the app will launch to the last previously "viewed" printer instead of the one specified in the print progress notification.

Can we instead open the app to the current applicable 3D printer from the app notification?

**Comment by Clon1998** [comment]
Greetings! I recently found a moment to investigate and successfully re-implemented the function of switching to the printer that corresponds with the notification once the user taps on it.  
It will be included in the next release!
