### ISSUE TITLE
Add firmware retraction settings

### ISSUE THREAD

**Issue by carhifitrier** [Clon1998/mobileraker#129]
First, **thanks** for your work, i appreciate it! 

Would love to see settings for firmware retraction in a future release.
Cheers, Alex

**Comment by Primus007** [comment]
+1
Yes, please add settings for firmware retraction.

**Comment by Clon1998** [comment]
Was about to create a issue to remind me that I need to add this haha.

Will include it in the next release 😀

**Comment by kohbo** [comment]
close? @Clon1998

**Comment by Clon1998** [comment]
> close? @Clon1998 

Ohh right haha.
Thanks for the hint
