### ISSUE TITLE
Octoeverywhere IOS

### ISSUE THREAD

**Issue by pinolt** [Clon1998/mobileraker#131]
It seems like Octoeverywhere is only available for android (based off of the integration instructions from Octoeverywhere). 

Will you be implementing their platform?

**Comment by Clon1998** [comment]
Hey,
Quin (Author of OE) implemented the redirect on his website based on the device you are using.
OE will be available for both Android and IOS.
Just Yesterday i pushed a new release that contains all changes related to OE and that is currently waiting for approval by apple.

**Comment by pinolt** [comment]
Great, thanky you for the prompt response Patrick.

Love the app btw, great UX/UI design.
