### ISSUE TITLE
Support for authorization header

### ISSUE THREAD

**Issue by mnestor** [Clon1998/mobileraker#134]
**Is your feature request related to a problem? Please describe.**
I have exposed my mainsail website to the internet through an authentication proxy instead of doing VPN since my workplace blocks VPNs

**Describe the solution you'd like**
Authorization header support, or even generic header support. With maintaining the session cookie so authentication doesn't need to happen for every request. Additionally this should share the cookie with the webcam if they have the same domain.

**Describe alternatives you've considered**
Setting up basic authentication with my auth proxy and adding the user/pass to the url https://user:pass@klipper.home
This does work but I don't feel comfortable with this implementation and it does have random errors being able to connect.

**Additional context**
Moving from the wrong location because my dumb self wasn't paying attention Clon1998/mobileraker_companion#24

**Comment by Clon1998** [comment]
Added in [android2.5.0](https://github.com/Clon1998/mobileraker/tree/android2.5.0)
