### ISSUE TITLE
mobile does not honor max_temp value for fan's

### ISSUE THREAD

**Issue by BlackNet** [Clon1998/mobileraker#139]
declaring max_temp: 60  for use on the chamber exhaust fan, or any other temperature_fan and others.  Then using the mobile app to set the fan temp it uses 0-100 and not 0-max_temp, thus overriding max_temp value resulting in gcode errors:   

_**### Requested temperature (100.0) out of range (0.0:60.0)**_

**Comment by Clon1998** [comment]
Added in [2.3.0](https://github.com/Clon1998/mobileraker/releases/tag/android2.3.0)
