### ISSUE TITLE
Output Pin "Caselight" unable to set to anything but 10%

### ISSUE THREAD

**Issue by cpiercedev** [Clon1998/mobileraker#14]
No matter what value is entered, it always defaults to 10%.

https://user-images.githubusercontent.com/43823548/130495171-9a2f34ff-9bf0-4eb7-aeda-2d6d2dfb6f7c.MP4

**Comment by Clon1998** [comment]
Can you post your output config from klipper?

**Comment by cpiercedev** [comment]
[output_pin caselight ]
pin: P2.5
pwm: true
value: 100
cycle_time: 0.01
shutdown_value: 0

scale: 100

**Comment by Clon1998** [comment]
Thanks for that.
The bug is related to your scale.
Currently, the app defaults to a 10 scale.
I will have to extend the config parsing on my app in order to get this working properly.
I Will add this to my todos, but this should be a rather easy and fast fix :).
Thanks for your feedback!.
