### ISSUE TITLE
Heater_generic is not shown in the temperature section.

### ISSUE THREAD

**Issue by salbang** [Clon1998/mobileraker#140]
**Is your feature request related to a problem? Please describe.**
Temperature of [heater_generic ...] is not shown in the tempetature section.

**Describe the solution you'd like**
It would be nice if the tempetature reading from the heater_generic is shown together with extruder, heater_bed, and other tempetature sensors.
In addition it would be better if I can set the temperature target for heater_generic.

**Describe alternatives you've considered**
Mainsail mobile web.

**Additional context**
![image](https://user-images.githubusercontent.com/12740762/229818540-02b3bd74-70c5-4607-94c6-4a856d9790a5.png)
![image](https://user-images.githubusercontent.com/12740762/229818820-1b9ce0cd-4933-4a89-94a9-c805a8d5ec35.png)

**Comment by salbang** [comment]
Temperature of z_thermal_adjust is not shown, either.
![IMG_03973F6C46B3-1](https://github.com/Clon1998/mobileraker/assets/12740762/41775cbc-b90d-40cd-9c54-f26ae0d7226a)

**Comment by Clon1998** [comment]
Hey,
sorry for my late reply. Are you still talking about a generic heater?

**Comment by salbang** [comment]
This time it is about 
[z_thermal_adjust]
This section is also related to temperature. 
![image](https://github.com/Clon1998/mobileraker/assets/12740762/54b8fb2d-f874-436a-94e1-e55ef4e4dc62)
