### ISSUE TITLE
Exception Related to "Exclude_Object"

### ISSUE THREAD

**Issue by sabaatworld** [Clon1998/mobileraker#142]
**Describe the bug**
I recently switched to using Orca Slicer. Whenever a print is in progress with GCODE generated using the latest version (v1.6.1) of the slicer, and I bring the app to foreground, I see this error being logged. Attaching screenshots and GCODE file.

[error.log](https://github.com/Clon1998/mobileraker/files/11185414/error.log)
[body-2_PETG_2h48m.gcode.txt](https://github.com/Clon1998/mobileraker/files/11185416/body-2_PETG_2h48m.gcode.txt)

**To Reproduce**
1. Start print using GCODE generated by Orca Slicer.
2. Either open app for first time or bring it to foreground from background.
3. The error can be seen. It does not seem to impact any functionality though.

**Expected behavior**
No error should be seen.

**Screenshots**
![IMG_2738](https://user-images.githubusercontent.com/2452471/230771888-fd476e85-bcc9-40a9-acfb-7c8e1f1d0972.png)
![IMG_2737](https://user-images.githubusercontent.com/2452471/230771895-5ce6c44e-ba98-4624-8c92-6b73c16210fe.png)

**Smartphone (please complete the following information):**
 - Device: iPhone 12 Pro
 - OS: 16.4
 - Version Latest

**Mobileraker-Version
Latest

**Additional context**
N/A

**Comment by Clon1998** [comment]
Fixed in 14e6453.
Release (2.2.2) should be available in the next few hours.
