### ISSUE TITLE
[Suggestion] App, Rename "Restart Klipper" or "Restart MCU" to Firmware Restart?

### ISSUE THREAD

**Issue by devsfan1830** [Clon1998/mobileraker#145]
In the event I use the emergency stop when a print failure occurs, i am directed by klipper to select firmware restart but the mobileraker app presents the aforementioned options instead. I am CONSISTENTLY picking the wrong one and doing a full pi reboot. Just asking for a bit of terminology consistency to perhaps rename whatever thw correct option is to "Firmware Restart". Minor complaint i know. Just throwing out the request.

**Comment by Clon1998** [comment]
Added in [2.3.0](https://github.com/Clon1998/mobileraker/releases/tag/android2.3.0)
