### ISSUE TITLE
Octoeverywhere with Moonraker - API key

### ISSUE THREAD

**Issue by dushanL** [Clon1998/mobileraker#146]
I have linked octoeverywhere to mobileraker. When mobileraker is out of local network, i receive warning message: "It seems like you configured trusted clients for Moonraker. Please add the API key in the printers setting!"
In moonraker.conf is force_logins: True, on local network work fine.  

If i disable force_logins octoeverywhere link work fine out of local network.

moonraker - v0.8.0-32-g31e589a
klipper - v0.11.0-173-ga8b1b0ef
octoeverywhere - 2.5.2-0-ge083fd4
mobileraker android version - 2.2.3
Device: Samsung Galaxy S22
OS: Android 13

**Comment by Clon1998** [comment]
Hey, afaik that's exactly how the force login is supposed to work. However, you might wanna check with the ocotoeverywhere team to verify that. 
Did you try to add the API key to mobileraker? It should resolve this issue.

**Comment by dushanL** [comment]
Yes, I have an API key in mobileraker.  With this setting, force login works for me only on the local network. 
![Screenshot_20230419_170700](https://user-images.githubusercontent.com/126228438/233121285-22444c64-0af6-46f6-805a-1481f2e69cc9.png)

I have an error via octoeverywhere.
![Screenshot_20230419_170803](https://user-images.githubusercontent.com/126228438/233122593-8a3034a4-c389-4822-8125-1f2ffbd9154e.jpg)

**Comment by Clon1998** [comment]
I see,
I will look into that.

**Comment by mattconn24** [comment]
I can confirm that I am also having this same issue.

**Comment by Clon1998** [comment]
> I can confirm that I am also having this same issue on my iPhone 14.

I am in contact with the author of OE. We are currently investigating.

**Comment by Clon1998** [comment]
Short update:
I have found the potential problem on my side that prevented the usage of the API Key while using OE.
At the same time, the author of OE also figured out that on his side the implementation is/was missing.
I hope we can resolve that in the next week.

**Comment by mattconn24** [comment]
Get news!  Thank you for the amazing work on this app.

**Comment by Chris-Epler** [comment]
Wondering if there is an update on this and while troubleshooting it I noticed when I tried to scan the QR code from the web interface of Moonraker for the API key that it wasn't updating it and I had to type in the API key manually...

**Comment by Clon1998** [comment]
> Wondering if there is an update on this and while troubleshooting it I noticed when I tried to scan the QR code from the web interface of Moonraker for the API key that it wasn't updating it and I had to type in the API key manually...

Are you talking about the QR not getting inserted into the correct field in the app?
If that is the case, this is not related

**Comment by Clon1998** [comment]
I just triggered the build for Mobileraker v2.2.6. According to my testing, it should resolve any missing implementation regarding the API key for Octoeverywhere.
After chatting with the OE dev, he added full support for authed sockets in the OE client version 2.5.5. 
If you guys have any problem regarding Mobileraker+Oe with the API Key, please comment on this issue and I will reopen it.

**Comment by Clon1998** [comment]
Added in [2.3.0](https://github.com/Clon1998/mobileraker/releases/tag/android2.3.0)
