### ISSUE TITLE
Mobileraker won't connect to the printer

### ISSUE THREAD

**Issue by 110Tim706** [Clon1998/mobileraker#149]
![image](https://user-images.githubusercontent.com/88311837/234632254-25f95159-86cf-4492-983d-9601c0a17ee6.png)![image](https://user-images.githubusercontent.com/88311837/234632269-9a289453-bd50-4537-8b89-e2b71a64d580.png)
I don't know what I did wrong but I'm sure i screwed up. Anyone can give me a hint?

**Comment by Clon1998** [comment]
Please make sure you provide the correct path to the websocket.
In case you did not modify it, it should be located at `/websocket`.
E.g: `ws://192.168.178.135/websocket `
