### ISSUE TITLE
Mobileraker iOS app gcode thumbnails error

### ISSUE THREAD

**Issue by Hr-Ravn** [Clon1998/mobileraker#150]
Having issues with getting gcode thumbnails to show in mobileraker iOS App.
Working fine on browser!

Getting following errors in the log in iOS app

What can i do about that?

`[[38;5;196m⛔ HttpException: Invalid statusCode: 404, uri = http://192.168.87.175///server/files/gcodes/PLA/.thumbs/laptop_stand_remake-400x400.png[0m]
[[38;5;208m⚠️ http://192.168.87.175///server/files/gcodes/PLA/.thumbs/laptop_stand_remake-400x400.png[0m]
[[38;5;196m⛔ HttpException: Invalid statusCode: 404, uri = http://192.168.87.175///server/files/gcodes/PLA/.thumbs/laptop_stand_remake-400x400.png[0m]
[[38;5;208m⚠️ http://192.168.87.175///server/files/gcodes/PLA/.thumbs/laptop_stand_remake-400x400.png[0m]
[[38;5;196m⛔ HttpException: Invalid statusCode: 404, uri = http://192.168.87.175///server/files/gcodes/PLA/.thumbs/laptop_stand_remake-400x400.png[0m]
[[38;5;208m⚠️ http://192.168.87.175///server/files/gcodes/PLA/.thumbs/laptop_stand_remake-400x400.png[0m]
[[38;5;196m⛔ HttpException: Invalid statusCode: 404, uri = http://192.168.87.175///server/files/gcodes/PLA/.thumbs/laptop_stand_remake-400x400.png[0m]
[[38;5;208m⚠️ http://192.168.87.175///server/files/gcodes/PLA/.thumbs/laptop_stand_remake-400x400.png[0m]
[[38;5;196m⛔ HttpException: Invalid statusCode: 404, uri = http://192.168.87.175///server/files/gcodes/PLA/.thumbs/laptop_stand_remake-400x400.png[0m]
[[38;5;208m⚠️ http://192.168.87.175///server/files/gcodes/PLA/.thumbs/Shape-Box_120-400x400.png[0m]
[[38;5;196m⛔ HttpException: Invalid statusCode: 404, uri = http://192.168.87.175///server/files/gcodes/PLA/.thumbs/Shape-Box_120-400x400.png[0m]
[[38;5;208m⚠️ http://192.168.87.175///server/files/gcodes/PLA/.thumbs/sb_adxl_mount_generic_15.5mm_c_c-400x400.png[0m]
[[38;5;196m⛔ HttpException: Invalid statusCode: 404, uri = http://192.168.87.175///server/files/gcodes/PLA/.thumbs/sb_adxl_mount_generic_15.5mm_c_c-400x400.png[0m]
[[38;5;208m⚠️ http://192.168.87.175///server/files/gcodes/PLA/.thumbs/Shape-Box_120-400x400.png[0m]
[[38;5;196m⛔ HttpException: Invalid statusCode: 404, uri = http://192.168.87.175///server/files/gcodes/PLA/.thumbs/Shape-Box_120-400x400.png[0m]
[[38;5;208m⚠️ http://192.168.87.175///server/files/gcodes/PLA/.thumbs/sb_adxl_mount_generic_15.5mm_c_c-400x400.png[0m]
[[38;5;196m⛔ HttpException: Invalid statusCode: 404, uri = http://192.168.87.175///server/files/gcodes/PLA/.thumbs/sb_adxl_mount_generic_15.5mm_c_c-400x400.png[0m]
[[38;5;208m⚠️ http://192.168.87.175///server/files/gcodes/PLA/.thumbs/laptop_stand_remake-400x400.png[0m]
[[38;5;196m⛔ HttpException: Invalid statusCode: 404, uri = http://192.168.87.175///server/files/gcodes/PLA/.thumbs/laptop_stand_remake-400x400.png[0m]
[[38;5;208m⚠️ http://192.168.87.175///server/files/gcodes/PLA/.thumbs/Shape-Box_120-400x400.png[0m]
[[38;5;196m⛔ HttpException: Invalid statusCode: 404, uri = http://192.168.87.175///server/files/gcodes/PLA/.thumbs/Shape-Box_120-400x400.png[0m]
[[38;5;208m⚠️ http://192.168.87.175///server/files/gcodes/PLA/.thumbs/sb_adxl_mount_generic_15.5mm_c_c-400x400.png[0m]
[[38;5;196m⛔ HttpException: Invalid statusCode: 404, uri = http://192.168.87.175///server/files/gcodes/PLA/.thumbs/sb_adxl_mount_generic_15.5mm_c_c-400x400.png[0m]
[[38;5;208m⚠️ http://192.168.87.175///server/files/gcodes/PLA/.thumbs/laptop_stand_remake-400x400.png[0m]
[[38;5;196m⛔ HttpException: Invalid statusCode: 404, uri = http://192.168.87.175///server/files/gcodes/PLA/.thumbs/laptop_stand_remake-400x400.png[0m]
[[38;5;208m⚠️ http://192.168.87.175///server/files/gcodes/PLA/.thumbs/laptop_stand_remake-400x400.png[0m]
[[38;5;196m⛔ HttpException: Invalid statusCode: 404, uri = http://192.168.87.175///server/files/gcodes/PLA/.thumbs/laptop_stand_remake-400x400.png[0m]
[[38;5;208m⚠️ http://192.168.87.175///server/files/gcodes/PLA/.thumbs/laptop_stand_remake-400x400.png[0m]
[[38;5;196m⛔ HttpException: Invalid statusCode: 404, uri = http://192.168.87.175///server/files/gcodes/PLA/.thumbs/laptop_stand_remake-400x400.png[0m]
[[38;5;208m⚠️ http://192.168.87.175///server/files/gcodes/PLA/.thumbs/laptop_stand_remake-400x400.png[0m]
[[38;5;196m⛔ HttpException: Invalid statusCode: 404, uri = http://192.168.87.175///server/files/gcodes/PLA/.thumbs/laptop_stand_remake-400x400.png[0m]
[[38;5;208m⚠️ http://192.168.87.175///server/files/gcodes/PLA/.thumbs/laptop_stand_remake-400x400.png[0m]
[[38;5;196m⛔ HttpException: Invalid statusCode: 404, uri = http://192.168.87.175///server/files/gcodes/PLA/.thumbs/laptop_stand_remake-400x400.png[0m]
[[38;5;208m⚠️ http://192.168.87.175///server/files/gcodes/PLA/.thumbs/laptop_stand_remake-400x400.png[0m]
[[38;5;196m⛔ HttpException: Invalid statusCode: 404, uri = http://192.168.87.175///server/files/gcodes/PLA/.thumbs/laptop_stand_remake-400x400.png[0m]
[[38;5;208m⚠️ http://192.168.87.175///server/files/gcodes/PLA/.thumbs/laptop_stand_remake-400x400.png[0m]
[[38;5;196m⛔ HttpException: Invalid statusCode: 404, uri = http://192.168.87.175///server/files/gcodes/PLA/.thumbs/laptop_stand_remake-400x400.png[0m]
[[38;5;208m⚠️ http://192.168.87.175///server/files/gcodes/PLA/.thumbs/laptop_stand_remake-400x400.png[0m]
[[38;5;196m⛔ HttpException: Invalid statusCode: 404, uri = http://192.168.87.175///server/files/gcodes/PLA/.thumbs/laptop_stand_remake-400x400.png[0m]
[[38;5;208m⚠️ http://192.168.87.175///server/files/gcodes/PLA/.thumbs/laptop_stand_remake-400x400.png[0m]
[[38;5;196m⛔ HttpException: Invalid statusCode: 404, uri = http://192.168.87.175///server/files/gcodes/PLA/.thumbs/laptop_stand_remake-400x400.png[0m]
[[38;5;208m⚠️ http://192.168.87.175///server/files/gcodes/PLA/.thumbs/laptop_stand_remake-400x400.png[0m]
[[38;5;196m⛔ HttpException: Invalid statusCode: 404, uri = http://192.168.87.175///server/files/gcodes/PLA/.thumbs/laptop_stand_remake-400x400.png[0m]
[[38;5;208m⚠️ http://192.168.87.175///server/files/gcodes/PLA/.thumbs/laptop_stand_remake-400x400.png[0m]
[[38;5;196m⛔ HttpException: Invalid statusCode: 404, uri = http://192.168.87.175///server/files/gcodes/PLA/.thumbs/laptop_stand_remake-400x400.png[0m]
[[38;5;208m⚠️ http://192.168.87.175///server/files/gcodes/PLA/.thumbs/laptop_stand_remake-400x400.png[0m]
[[38;5;196m⛔ HttpException: Invalid statusCode: 404, uri = http://192.168.87.175///server/files/gcodes/PLA/.thumbs/laptop_stand_remake-400x400.png[0m]
[[38;5;208m⚠️ http://192.168.87.175///server/files/gcodes/PLA/.thumbs/laptop_stand_remake-400x400.png[0m]
[[38;5;196m⛔ HttpException: Invalid statusCode: 404, uri = http://192.168.87.175///server/files/gcodes/PLA/.thumbs/laptop_stand_remake-400x400.png[0m]
[[38;5;208m⚠️ http://192.168.87.175///server/files/gcodes/PLA/.thumbs/laptop_stand_remake-400x400.png[0m]
[[38;5;196m⛔ HttpException: Invalid statusCode: 404, uri = http://192.168.87.175///server/files/gcodes/PLA/.thumbs/laptop_stand_remake-400x400.png[0m]
[[38;5;208m⚠️ http://192.168.87.175///server/files/gcodes/PLA/.thumbs/laptop_stand_remake-400x400.png[0m]
[[38;5;196m⛔ HttpException: Invalid statusCode: 404, uri = http://192.168.87.175///server/files/gcodes/PLA/.thumbs/laptop_stand_remake-400x400.png[0m]
[[38;5;208m⚠️ http://192.168.87.175///server/files/gcodes/PLA/.thumbs/laptop_stand_remake-400x400.png[0m]
[[38;5;196m⛔ HttpException: Invalid statusCode: 404, uri = http://192.168.87.175///server/files/gcodes/PLA/.thumbs/laptop_stand_remake-400x400.png[0m]
[[38;5;208m⚠️ http://192.168.87.175///server/files/gcodes/PLA/.thumbs/laptop_stand_remake-400x400.png[0m]
[[38;5;196m⛔ HttpException: Invalid statusCode: 404, uri = http://192.168.87.175///server/files/gcodes/PLA/.thumbs/laptop_stand_remake-400x400.png[0m]
[[38;5;208m⚠️ http://192.168.87.175///server/files/gcodes/PLA/.thumbs/laptop_stand_remake-400x400.png[0m]
[[38;5;196m⛔ HttpException: Invalid statusCode: 404, uri = http://192.168.87.175///server/files/gcodes/PLA/.thumbs/laptop_stand_remake-400x400.png[0m]
[[38;5;208m⚠️ http://192.168.87.175///server/files/gcodes/PLA/.thumbs/laptop_stand_remake-400x400.png[0m]
[[38;5;196m⛔ HttpException: Invalid statusCode: 404, uri = http://192.168.87.175///server/files/gcodes/PLA/.thumbs/laptop_stand_remake-400x400.png[0m]
[[38;5;208m⚠️ http://192.168.87.175///server/files/gcodes/PLA/.thumbs/laptop_stand_remake-400x400.png[0m]
[[38;5;196m⛔ HttpException: Invalid statusCode: 404, uri = http://192.168.87.175///server/files/gcodes/PLA/.thumbs/laptop_stand_remake-400x400.png[0m]
[[38;5;208m⚠️ http://192.168.87.175///server/files/gcodes/PLA/.thumbs/laptop_stand_remake-400x400.png[0m]
[[38;5;196m⛔ HttpException: Invalid statusCode: 404, uri = http://192.168.87.175///server/files/gcodes/PLA/.thumbs/laptop_stand_remake-400x400.png[0m]
[[38;5;208m⚠️ http://192.168.87.175///server/files/gcodes/PLA/.thumbs/laptop_stand_remake-400x400.png[0m]
[[38;5;196m⛔ HttpException: Invalid statusCode: 404, uri = http://192.168.87.175///server/files/gcodes/PLA/.thumbs/laptop_stand_remake-400x400.png[0m]
[[38;5;208m⚠️ http://192.168.87.175///server/files/gcodes/PLA/.thumbs/laptop_stand_remake-400x400.png[0m]
[[38;5;196m⛔ HttpException: Invalid statusCode: 404, uri = http://192.168.87.175///server/files/gcodes/PLA/.thumbs/laptop_stand_remake-400x400.png[0m]
[[38;5;208m⚠️ http://192.168.87.175///server/files/gcodes/PLA/.thumbs/laptop_stand_remake-400x400.png[0m]
[[38;5;196m⛔ HttpException: Invalid statusCode: 404, uri = http://192.168.87.175///server/files/gcodes/PLA/.thumbs/laptop_stand_remake-400x400.png[0m]
[[38;5;208m⚠️ http://192.168.87.175///server/files/gcodes/PLA/.thumbs/laptop_stand_remake-400x400.png[0m]
[[38;5;196m⛔ HttpException: Invalid statusCode: 404, uri = http://192.168.87.175///server/files/gcodes/PLA/.thumbs/laptop_stand_remake-400x400.png[0m]
[[38;5;208m⚠️ http://192.168.87.175///server/files/gcodes/PLA/.thumbs/laptop_stand_remake-400x400.png[0m]
[[38;5;196m⛔ HttpException: Invalid statusCode: 404, uri = http://192.168.87.175///server/files/gcodes/PLA/.thumbs/laptop_stand_remake-400x400.png[0m]
[[38;5;208m⚠️ http://192.168.87.175///server/files/gcodes/PLA/.thumbs/laptop_stand_remake-400x400.png[0m]
[[38;5;196m⛔ HttpException: Invalid statusCode: 404, uri = http://192.168.87.175///server/files/gcodes/PLA/.thumbs/laptop_stand_remake-400x400.png[0m]
[[38;5;208m⚠️ http://192.168.87.175///server/files/gcodes/PLA/.thumbs/laptop_stand_remake-400x400.png[0m]
[[38;5;196m⛔ HttpException: Invalid statusCode: 404, uri = http://192.168.87.175///server/files/gcodes/PLA/.thumbs/laptop_stand_remake-400x400.png[0m]
[[38;5;208m⚠️ http://192.168.87.175///server/files/gcodes/PLA/.thumbs/laptop_stand_remake-400x400.png[0m]
[[38;5;196m⛔ HttpException: Invalid statusCode: 404, uri = http://192.168.87.175///server/files/gcodes/PLA/.thumbs/laptop_stand_remake-400x400.png[0m]
[[38;5;208m⚠️ http://192.168.87.175///server/files/gcodes/PLA/.thumbs/laptop_stand_remake-400x400.png[0m]
[[38;5;196m⛔ HttpException: Invalid statusCode: 404, uri = http://192.168.87.175///server/files/gcodes/PLA/.thumbs/laptop_stand_remake-400x400.png[0m]
[[38;5;208m⚠️ http://192.168.87.175///server/files/gcodes/PLA/.thumbs/laptop_stand_remake-400x400.png[0m]
[[38;5;196m⛔ HttpException: Invalid statusCode: 404, uri = http://192.168.87.175///server/files/gcodes/PLA/.thumbs/laptop_stand_remake-400x400.png[0m]
[[38;5;12m💡 Getting settings[0m]
[[38;5;208m⚠️ http://192.168.87.175///server/files/gcodes/PLA/.thumbs/sb_adxl_mount_generic_15.5mm_c_c-400x400.png[0m]
[[38;5;196m⛔ HttpException: Invalid statusCode: 404, uri = http://192.168.87.175///server/files/gcodes/PLA/.thumbs/sb_adxl_mount_generic_15.5mm_c_c-400x400.png[0m]
[[38;5;208m⚠️ http://192.168.87.175///server/files/gcodes/PLA/.thumbs/Shape-Box_120-400x400.png[0m]
[[38;5;196m⛔ HttpException: Invalid statusCode: 404, uri = http://192.168.87.175///server/files/gcodes/PLA/.thumbs/Shape-Box_120-400x400.png[0m]
[[38;5;208m⚠️ http://192.168.87.175///server/files/gcodes/PLA/.thumbs/laptop_stand_remake-400x400.png[0m]
[[38;5;196m⛔ HttpException: Invalid statusCode: 404, uri = http://192.168.87.175///server/files/gcodes/PLA/.thumbs/laptop_stand_remake-400x400.png[0m]
[[38;5;208m⚠️ http://192.168.87.175///server/files/gcodes/PLA/.thumbs/laptop_stand_remake-400x400.png[0m]
[[38;5;196m⛔ HttpException: Invalid statusCode: 404, uri = http://192.168.87.175///server/files/gcodes/PLA/.thumbs/laptop_stand_remake-400x400.png[0m]
[[38;5;208m⚠️ http://192.168.87.175///server/files/gcodes/PLA/.thumbs/Shape-Box_120-400x400.png[0m]
[[38;5;196m⛔ HttpException: Invalid statusCode: 404, uri = http://192.168.87.175///server/files/gcodes/PLA/.thumbs/Shape-Box_120-400x400.png[0m]
[[38;5;208m⚠️ http://192.168.87.175///server/files/gcodes/PLA/.thumbs/sb_adxl_mount_generic_15.5mm_c_c-400x400.png[0m]
[[38;5;196m⛔ HttpException: Invalid statusCode: 404, uri = http://192.168.87.175///server/files/gcodes/PLA/.thumbs/sb_adxl_mount_generic_15.5mm_c_c-400x400.png[0m]
[[38;5;208m⚠️ http://192.168.87.175///server/files/gcodes/PLA/.thumbs/laptop_stand_remake-400x400.png[0m]
[[38;5;196m⛔ HttpException: Invalid statusCode: 404, uri = http://192.168.87.175///server/files/gcodes/PLA/.thumbs/laptop_stand_remake-400x400.png[0m]
[[38;5;208m⚠️ http://192.168.87.175///server/files/gcodes/PLA/.thumbs/Shape-Box_120-400x400.png[0m]
[[38;5;196m⛔ HttpException: Invalid statusCode: 404, uri = http://192.168.87.175///server/files/gcodes/PLA/.thumbs/Shape-Box_120-400x400.png[0m]
[[38;5;208m⚠️ http://192.168.87.175///server/files/gcodes/PLA/.thumbs/sb_adxl_mount_generic_15.5mm_c_c-400x400.png[0m]
[[38;5;196m⛔ HttpException: Invalid statusCode: 404, uri = http://192.168.87.175///server/files/gcodes/PLA/.thumbs/sb_adxl_mount_generic_15.5mm_c_c-400x400.png[0m]
[[38;5;208m⚠️ -DISPOSED printerSelected[0m]
[[38;5;12m💡 Getting settings[0m]
[[38;5;12m💡 Start MJPEG - targFps: 15 - http://192.168.87.175/webcam/?action=stream[0m]
[[38;5;12m💡 [ws://100.64.143.29/websocket] WS not connected! connecting...[0m]
[[38;5;12m💡 [300574935]Trying to connect to ws://100.64.143.29/websocket[0m]
[[38;5;12m💡 [300574935-ws://100.64.143.29/websocket] ClientState.error ➝ ClientState.connecting[0m]
[[38;5;12m💡 Start MJPEG - targFps: 15 - http://100.64.143.29/webcam/?action=stream[0m]
[[38;5;208m⚠️ Got channel error SocketException: HTTP connection timed out after 0:00:03.000000, host: 100.64.143.29, port: 80[0m]
[[38;5;196m⛔ [ws://100.64.143.29/websocket300574935] WS-Stream error: SocketException: HTTP connection timed out after 0:00:03.000000, host: 100.64.143.29, port: 80[0m]
[[38;5;12m💡 [300574935-ws://100.64.143.29/websocket] ClientState.connecting ➝ ClientState.error[0m]
[[38;5;196m⛔ ääää AsyncData<ClientState>(value: ClientState.error)[0m]
[[38;5;12m💡 Selecting machine Pumpkin[0m]
[[38;5;12m💡 Start MJPEG - targFps: 15 - http://192.168.87.175/webcam/?action=stream[0m]
[[38;5;12m💡 Getting meta for file: `ASA/V0/Frame/3510_Side_Skirt_Mid_x2.gcode`[0m]
[[38;5;12m💡 Stop MJPEG[0m]
[[38;5;12m💡 _AdaptiveStreamManager DISPOSED[0m]
[[38;5;12m💡 Stop MJPEG[0m]
[[38;5;12m💡 _AdaptiveStreamManager DISPOSED[0m]
[[38;5;12m💡 App in AppLifecycleState.inactive[0m]
[[38;5;12m💡 App backgrounded[0m]
[[38;5;12m💡 Stop MJPEG[0m]
[[38;5;12m💡 [ws://192.168.87.175/websocket885665478] WS-Stream closed normal! Code: 1002, Reason: null[0m]
[[38;5;12m💡 [885665478-ws://192.168.87.175/websocket] ClientState.connected ➝ ClientState.disconnected[0m]
[[38;5;12m💡 [885665478]Trying to connect to ws://192.168.87.175/websocket[0m]
[[38;5;12m💡 [885665478-ws://192.168.87.175/websocket] ClientState.disconnected ➝ ClientState.connecting[0m]
[[38;5;196m⛔ ääää AsyncData<ClientState>(value: ClientState.disconnected)[0m]
[[38;5;12m💡 App in AppLifecycleState.inactive[0m]
[[38;5;12m💡 Stop MJPEG[0m]
[[38;5;12m💡 _AdaptiveStreamManager DISPOSED[0m]
[[38;5;12m💡 [885665478-ws://192.168.87.175/websocket] ClientState.connecting ➝ ClientState.connected[0m]
[[38;5;12m💡 >>>Fetching Server.Info[0m]
[[38;5;12m💡 >>>Fetching Printer.Info[0m]
[[38;5;12m💡 <<<Received Server.Info[0m]
[[38;5;12m💡 Refreshing printer for uuid: 2ad2418f-1594-43f6-aeee-87de544ce9cb[0m]
[[38;5;12m💡 >>>Querying printers object list[0m]
[[38;5;12m💡 Getting settings[0m]
[[38;5;12m💡 Start MJPEG - targFps: 15 - http://192.168.87.175/webcam/?action=stream[0m]
[[38;5;12m💡 Getting meta for file: `ASA/V0/Frame/3510_Side_Skirt_Mid_x2.gcode`[0m]
[[38;5;12m💡 <<<Received Printer.Info[0m]
[[38;5;12m💡 Getting meta for file: `ASA/V0/Frame/3510_Side_Skirt_Mid_x2.gcode`[0m]
[[38;5;12m💡 Getting settings[0m]
[[38;5;12m💡 <<<Received printer objects list![0m]
[[38;5;12m💡 >>>Querying Printer Objects![0m]
[[38;5;12m💡 App forgrounded[0m]
[[38;5;12m💡 Refreshing selectedPrinter...[0m]
[[38;5;12m💡 No remote client configured... cant do handover! ref:432005510[0m]
[[38;5;12m💡 Start MJPEG - targFps: 15 - http://192.168.87.175/webcam/?action=stream[0m]
[[38;5;12m💡 <<<Received queried printer objects[0m]
[[38;5;12m💡 Fetching cached temperature store data[0m]
[[38;5;12m💡 Received cached temperature store for [temperature_sensor CHAMBER, temperature_sensor CR_4.2.2, heater_bed, temperature_sensor SKR_Mini_E3, temperature_sensor raspberry_pi, extruder][0m]
[[38;5;12m💡 Subscribing printer objects for ws-updates![0m]
[[38;5;12m💡 Updating Default Macros for "Pumpkin(ws://192.168.87.175/websocket)"![0m]
[[38;5;12m💡 Getting settings[0m]
[[38;5;12m💡 App in AppLifecycleState.inactive[0m]
[[38;5;12m💡 App backgrounded[0m]
[[38;5;12m💡 Stop MJPEG[0m]
[[38;5;12m💡 App in AppLifecycleState.inactive[0m]
[[38;5;12m💡 [ws://192.168.87.175/websocket885665478] WS-Stream closed normal! Code: 1005, Reason: [0m]
[[38;5;12m💡 [885665478-ws://192.168.87.175/websocket] ClientState.connected ➝ ClientState.disconnected[0m]
[[38;5;12m💡 [885665478]Trying to connect to ws://192.168.87.175/websocket[0m]
[[38;5;12m💡 [885665478-ws://192.168.87.175/websocket] ClientState.disconnected ➝ ClientState.connecting[0m]
[[38;5;196m⛔ ääää AsyncData<ClientState>(value: ClientState.disconnected)[0m]
[[38;5;12m💡 Stop MJPEG[0m]
[[38;5;12m💡 _AdaptiveStreamManager DISPOSED[0m]
[[38;5;12m💡 [885665478-ws://192.168.87.175/websocket] ClientState.connecting ➝ ClientState.connected[0m]
[[38;5;12m💡 >>>Fetching Server.Info[0m]
[[38;5;12m💡 >>>Fetching Printer.Info[0m]
[[38;5;12m💡 <<<Received Server.Info[0m]
[[38;5;12m💡 Refreshing printer for uuid: 2ad2418f-1594-43f6-aeee-87de544ce9cb[0m]
[[38;5;12m💡 >>>Querying printers object list[0m]
[[38;5;12m💡 Getting settings[0m]
[[38;5;12m💡 <<<Received Printer.Info[0m]
[[38;5;12m💡 Start MJPEG - targFps: 15 - http://192.168.87.175/webcam/?action=stream[0m]
[[38;5;12m💡 Getting meta for file: `ASA/V0/Frame/3510_Side_Skirt_Mid_x2.gcode`[0m]
[[38;5;12m💡 Getting settings[0m]
[[38;5;12m💡 <<<Received printer objects list![0m]
[[38;5;12m💡 >>>Querying Printer Objects![0m]
[[38;5;12m💡 App forgrounded[0m]
[[38;5;12m💡 Refreshing selectedPrinter...[0m]
[[38;5;12m💡 No remote client configured... cant do handover! ref:432005510[0m]
[[38;5;12m💡 Start MJPEG - targFps: 15 - http://192.168.87.175/webcam/?action=stream[0m]
[[38;5;12m💡 <<<Received queried printer objects[0m]
[[38;5;12m💡 Fetching cached temperature store data[0m]
[[38;5;12m💡 Received cached temperature store for [temperature_sensor CHAMBER, temperature_sensor CR_4.2.2, heater_bed, temperature_sensor SKR_Mini_E3, temperature_sensor raspberry_pi, extruder][0m]
[[38;5;12m💡 Subscribing printer objects for ws-updates![0m]
[[38;5;12m💡 Updating Default Macros for "Pumpkin(ws://192.168.87.175/websocket)"![0m]
[[38;5;12m💡 Getting settings[0m]
[[38;5;12m💡 Stop MJPEG[0m]
[[38;5;12m💡 _AdaptiveStreamManager DISPOSED[0m]
[[38;5;208m⚠️ -DISPOSED printerSelected[0m]
[[38;5;12m💡 Start MJPEG - targFps: 15 - http://192.168.87.175/webcam/?action=stream[0m]
[[38;5;12m💡 Getting meta for file: `ASA/V0/Frame/3510_Side_Skirt_Mid_x2.gcode`[0m]
[[38;5;12m💡 Getting settings[0m]
[[38;5;12m💡 Stop MJPEG[0m]
[[38;5;12m💡 _AdaptiveStreamManager DISPOSED[0m]
[[38;5;208m⚠️ -DISPOSED printerSelected[0m] `

**Comment by Hr-Ravn** [comment]
Don't know what was wrong, but a re-install of the app did solve the issue.

**Comment by Clon1998** [comment]
> Don't know what was wrong, but a re-install of the app did solve the issue.

First of all, I am glad that the issue resolved itself.

Here is however my take on the reasoning:
It seems like you misconfigured the **Printer - Address**

Have a look at the url that I copied from your log

http://192.168.87.175///server/files/gcodes/PLA/.thumbs/laptop_stand_remake-400x400.png

Somehow it contains three **///**, therefore the resolving of the image failed. 
I will reopen your issue and check how the app construct these URLs to ensure this won't happen again!
