### ISSUE TITLE
Remote notification on IOS devices with any action buttons or images

### ISSUE THREAD

**Issue by shaharhn** [Clon1998/mobileraker#151]
Hey Mr Patrick.
I am wondering if you get remote notifcation on IOS devices, i'm trying to use also awesome notifications fcm, and i couldn't manage to handle the remote notifications with actions or any 'special' usage. i only get the notification with title and body.

**Comment by Clon1998** [comment]
> Hey Mr Patrick. I am wondering if you get remote notifcation on IOS devices, i'm trying to use also awesome notifications fcm, and i couldn't manage to handle the remote notifications with actions or any 'special' usage. i only get the notification with title and body.

Hey, I have not tried any notifications with actions yet. All I am using is normal notifications with title and body. However, you should be able to check the logs of the IPhone that might contain additional info why your specific notification Is not showing

**Comment by shaharhn** [comment]
Thank you
