### ISSUE TITLE
Browse files while printer is offline

### ISSUE THREAD

**Issue by Jonisos** [Clon1998/mobileraker#163]
Hey,
would it be possible to browse files while the printer is offline but the server with klipper is running. Currently the app only shows the mcu error of being unable to connect. When using the web browser with Mainsail I can do said thing. 

Would be awesome to have since I often browse my recent uploads to check if I want to turn on the printer and finish some projects.

Thanks for the app!

**Comment by Clon1998** [comment]
Added in [android2.5.0](https://github.com/Clon1998/mobileraker/tree/android2.5.0)
