### ISSUE TITLE
Stuck on logo screen

### ISSUE THREAD

**Issue by ishtangli** [Clon1998/mobileraker#165]
Pixel 6 pro on android 13.

Just shows the logo on latest update.

**Comment by Clon1998** [comment]
Hey,
sadly I am unable to reproduce this issue with any scenario I can currently think of.
Therefore, can you please try to remove the app's locale data and retry starting the app?

**Comment by ishtangli** [comment]
How can I do that? Tried uninstalling, reinstalling, deleting cache.

**Comment by ishtangli** [comment]
Finally got it working by deleting the cache but NOT uninstalling the app.

**Comment by Clon1998** [comment]
> Finally got it working by deleting the cache but NOT uninstalling the app.

Hey,
sorry didn't get a notification earlier. I am glad it's working now for you!
Androids uninstall might not delete any of the saved files. Thefore clearing the cache worked.

I will look into that!
