### ISSUE TITLE
Webcam stream using webview

### ISSUE THREAD

**Issue by scmanjarrez** [Clon1998/mobileraker#167]
Hi, is it possible to add a webview that can load streams? I'm currently using go2rtc to get a streaming link using http. In mainsail I can use an iframe to load the stream, but I can't do that in mobileraker.

go2rtc url example: http://ip:1984/stream.html?src=camera
> This creates a WebRTC stream / browsers: all / codecs: H264, PCMU, PCMA, OPUS / +H265 in Safari

**Comment by Clon1998** [comment]
Added in [android2.5.0](https://github.com/Clon1998/mobileraker/tree/android2.5.0)
