### ISSUE TITLE
Timer alarm next to preheat button

### ISSUE THREAD

**Issue by joshtownsend66** [Clon1998/mobileraker#17]
Everytime i preheat a voron i pull out and set my timer to 5 minutes so ill know when to start. I want to be there to check the skirt at the start of a print. I would pay for this feature

**Comment by Clon1998** [comment]
So you want to get a notification once the printer is preheated through one of the presets?

**Comment by joshtownsend66** [comment]
That would work. I was thinking maybe linking it to the OS timer/clock or
something but anything like that. I forget to set my timer sometimes,
besides all the steps to get there and do it.

**Comment by Clon1998** [comment]
I will close the issue since this will be possible via the new custom `M117` user notifications supported through mobileraker_companion.
For more info and how to test the beta visit: https://github.com/Clon1998/mobileraker_companion/blob/dev/Custom_Notifications.md
