### ISSUE TITLE
Different color schemes for different printers

### ISSUE THREAD

**Issue by spott** [Clon1998/mobileraker#172]
When there are multiple printers, I sometimes forget which printer I’m on, and screw with the wrong one.  Being able to assign different colors to different printers would fix that.

This should be user selectable (so it can match the color scheme chosen in fluidd for example).

**Comment by Clon1998** [comment]
Added in [2.6.3](https://github.com/Clon1998/mobileraker/blob/master/docs/changelog.md#263---2023-09-15)
