### ISSUE TITLE
[Feature request] Support for Job queue

### ISSUE THREAD

**Issue by luisillo26** [Clon1998/mobileraker#173]
It would be great you could implement support for Job Queue, I mean the ability to add gcode files to the job queue, start printing, reorder, remove and set batch quantity to the Job Queue.

This feature is implemented in Mainsail and I believe is part of the moonraker api.

<img width="739" alt="image" src="https://github.com/Clon1998/mobileraker/assets/1028540/c7f9b223-90db-408b-b16c-39ff33f6932e">

![image](https://github.com/Clon1998/mobileraker/assets/1028540/1c7e62a1-876a-4685-9665-c8270a7a3d9a)

**Comment by Clon1998** [comment]
Here is a small preview of the JobQueue. I would love to get some feedback on it (Ignore some of the placeholders)

![image](https://github.com/Clon1998/mobileraker/assets/10357775/3e740254-8392-4e47-b14e-3e717cdea300)

![image](https://github.com/Clon1998/mobileraker/assets/10357775/6d87801f-5801-4d35-acf0-b8ff14499e7f)

**Comment by bitingsock** [comment]
Is this included in 2.6.3? will this add support for uploading gcode?

**Comment by Clon1998** [comment]
ohh yeah I am sorry missed that issue.
It was added in 2.6.2
