### ISSUE TITLE
Refresh Printer Error

### ISSUE THREAD

**Issue by renfordt** [Clon1998/mobileraker#181]
**Describe the bug**
App can't connect/refresh printer

**To Reproduce**
1. Open App
2. Error page is shown

**Expected behavior**
App connects to the printer without errors. 

**Screenshots**
![Screenshot_20230625-220531](https://github.com/Clon1998/mobileraker/assets/699163/0bd90720-3651-48b0-bc62-03f1f1389ef2)
![Screenshot_20230625-220551](https://github.com/Clon1998/mobileraker/assets/699163/6a0ff20c-008f-4a60-a92b-fcc1d9b79e8f)

**Smartphone (please complete the following information):**
 - Device: Google Pixel 4a
 - OS: Android 13
 - Browser: Various

**Mobileraker-Version**
2.4.1

**Additional context**
If more info is needed let me know.

**Comment by Clon1998** [comment]
Hey,
thanks for your Bug report.
I have already noticed that issue and fixed it in 03c3aca53ab3560006e29ee67577697a75b45bba, will be included in a fix later this week.
I am not 100% sure when Klipper goes into the `cancelled` state, but as soon as your printer is back to ready (Restart Klipper), or printing the app should work as expected.

**Comment by renfordt** [comment]
Thank you for your feedback.
In my case Klipper got int the cancelled state due to a failed END_PRINT Macro (Retract value higher than limit). Also it should be in the cancelled state when you manually cancel the print.

**Comment by Clon1998** [comment]
> Thank you for your feedback.
> 
> In my case Klipper got int the cancelled state due to a failed END_PRINT Macro (Retract value higher than limit). Also it should be in the cancelled state when you manually cancel the print.

Out of curiosity I checked when Klipper added this state. It was added more than a year ago and yet, I never encountered it and you are the first user reporting the problem.

**Comment by DrFate09** [comment]
@Clon1998 I believe I've also been seeing the same error. 

![Screenshot_20230626-115027](https://github.com/Clon1998/mobileraker/assets/22684695/db52a89b-f022-4858-980a-5c189888c174)
![Screenshot_20230626-115020](https://github.com/Clon1998/mobileraker/assets/22684695/275a9ec6-74c9-4689-9257-3722b5e3f552)

**Comment by Clon1998** [comment]
> @Clon1998 I believe I've also been seeing the same error.
> 
> ![Screenshot_20230626-115027](https://user-images.githubusercontent.com/22684695/249227196-db52a89b-f022-4858-980a-5c189888c174.png) ![Screenshot_20230626-115020](https://user-images.githubusercontent.com/22684695/249227247-275a9ec6-74c9-4689-9257-3722b5e3f552.png)

Hey,
no yours is different.

Does this happen all the time for you or just in a particular case?

**Comment by Clon1998** [comment]
Do you happen to have a `virtual_sdcard ` section in your config?

**Comment by DrFate09** [comment]
@Clon1998 I created a new issue 👍
