### ISSUE TITLE
No Dashboard without Setup a Camera

### ISSUE THREAD

**Issue by Avatarsia** [Clon1998/mobileraker#19]
The Dashboard is just showen with a Camera Setup, even with Printers that wont even have a camera

**Comment by Clon1998** [comment]
Please be sure the use the latest version v1.2.1.
This problem should be fixed in b163e17d6b02847be41358666c6a07583ef92f92

**Comment by Avatarsia** [comment]
just checked, yes there is an update available, maybe it's possible to include an update notification into the app ?
