### ISSUE TITLE
Webrtc/camera-streamer camera support 

### ISSUE THREAD

**Issue by definitely-not-a-t-rex** [Clon1998/mobileraker#191]
**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
 Since the latest crowsnest V4 moonraker allows for the use of webrtc and camera-streamer if you're using pis however the app only supports mjpg streamer, it'd nice to be able to use this better camera setup without breaking compatibility with the app.

**Comment by Clon1998** [comment]
Related to #167

**Comment by Clon1998** [comment]
Added in [android2.5.0](https://github.com/Clon1998/mobileraker/tree/android2.5.0)
