### ISSUE TITLE
Notification icon doesn't display correctly/at all

### ISSUE THREAD

**Issue by bengineer0013** [Clon1998/mobileraker#194]
**Describe the bug**
The square app icon in the notification doesn't expand to fill the circular space. When the notification is then expanded, the icon is replaced by a white square. 
[see screenshots]

**To Reproduce**
1. Simply have the printer send out a notification.

**Expected behavior**
The square logo should fill out the circle. When the notification is expanded, the icon should not change/disappear.

**Screenshots**
![Screenshot_2023-07-06-17-29-19-862_com miui home](https://github.com/Clon1998/mobileraker/assets/118354187/669349c4-2915-40f7-ac98-1440c2c5b2c7)
![Screenshot_2023-07-06-17-40-20-638_com android chrome-edit](https://github.com/Clon1998/mobileraker/assets/118354187/7ed7dcbe-a1c1-49db-b931-c04fe6904514)

**Smartphone (please complete the following information):**
 - Xiaomi Redmi Note 10 Pro
 - OS: MIUI 14.0.3 Android 13

**Mobileraker-Version**
2.4.2-219

**Comment by Clon1998** [comment]
Hey thanks for the bug report. I will look into that. I think I just referenced the wrong image here.

**Comment by Clon1998** [comment]
Should be fixed in [android2.5.0](https://github.com/Clon1998/mobileraker/tree/android2.5.0).
Please let me know if it works as soon as the new version is available trough google play (Might take 24-48 hrs)
