### ISSUE TITLE
Bed Mesh View

### ISSUE THREAD

**Issue by mahan518** [Clon1998/mobileraker#196]
Great Work!
Thank you!

Is there anyway to view a stored, or current, bed mesh? 

A section of the app that shows bed mesh like the attached photo would be amazing. 

If this feature is already there, my apologies, I was unable to find it. 

![image](https://github.com/Clon1998/mobileraker/assets/63216090/12e020ac-1829-49bd-b7a9-eb5d72315480)

**Comment by Clon1998** [comment]
Currently, the app does not support showing the mesh.

**Comment by Clon1998** [comment]
Added in 2.6.11
