### ISSUE TITLE
Ability to change ETA from 24hour to 12hour clock

### ISSUE THREAD

**Issue by fuzelet** [Clon1998/mobileraker#197]
**Is your feature request related to a problem? Please describe.**
I live in a country that uses 12 hour times such as 4:00PM. While it is not hard to change 24 hour clocks to AM/PM times, it would be nice if there was a feature to change the display shown in the ETA section of the application.

**Describe the solution you'd like**
Be able to show the ETA in 12 hour clock format instead of 24 hour clock.

**Describe alternatives you've considered**
Using a browser to check status of printer using the Mainsail webpage.

**Additional context**
ETA in Mainsail:
![Screenshot 2023-07-13 161419](https://github.com/Clon1998/mobileraker/assets/70331495/110f5fb6-2fe4-4f5f-b270-599d0337366f)

ETA in Mobileraker:
![Screenshot_20230713-160422](https://github.com/Clon1998/mobileraker/assets/70331495/ff63a3d5-e171-4ae7-b63c-b9bba92c8606)

**Comment by Clon1998** [comment]
Sure, adding that should be straightforward. I'll double-check to make sure that all time displays use either the 24 or 12-hour format, depending on what the user prefers.

**Comment by Clon1998** [comment]
Added in [android2.5.0](https://github.com/Clon1998/mobileraker/tree/android2.5.0)
