### ISSUE TITLE
Bed Screw Adjust: Buttons out of frame in small screen device.

### ISSUE THREAD

**Issue by GAZ082** [Clon1998/mobileraker#208]
I have a Sony XZ1 Compact. Has a 4.6" screen, 720p resolution.
![Screenshot_20230730-140957](https://github.com/Clon1998/mobileraker/assets/100194/57514e4f-d0a9-4f6b-b1bf-9a7a6e5554ab)

The buttons are outside the modal and I cant press them :(

**Comment by Clon1998** [comment]
Hey, 
Thank you for reporting the bug. It appears that I made a small mistake by forgetting to add shrinkage to the X/Y plane. I have already implemented a fix for this issue and it will be included in the next major release!

**Comment by GAZ082** [comment]
@Clon1998 hello Patrick I don't want to be a pain in the ass but wheb are you releasing the next version because this bug is making the app less useful for me right now 

Thanks!

**Comment by Clon1998** [comment]
> @Clon1998 hello Patrick I don't want to be a pain in the ass but wheb are you releasing the next version because this bug is making the app less useful for me right now
> 
> Thanks!

It still will take another week or two. Found a bug in the companion that requires my attention.
However, you can sideload a beta version that includes the hotfix if you need it right now (Also kindly confirm if the dialog is fixed)

https://github.com/Clon1998/mobileraker/releases/tag/pre-2.5.0

https://github.com/Clon1998/mobileraker/releases/download/pre-2.5.0/preview_b_2_5_0.apk

**Comment by GAZ082** [comment]
For some reason is not installing. I made sure to have space. I'm using Android 9, perhaps the manifest in this preview requires something newer by mistake? @Clon1998

**Comment by Clon1998** [comment]
Fixed in [android2.5.0](https://github.com/Clon1998/mobileraker/tree/android2.5.0)
