### ISSUE TITLE
App will not open on Samsung fold 5

### ISSUE THREAD

**Issue by cdeitrich00** [Clon1998/mobileraker#210]
**Describe the bug**
The app will not open past the logo screen on the samsung galaxy fold 5

**To Reproduce**
1. Download app on fold 5
2. Open app
3. Wait
4. Noting loads

**Expected behavior**
The app should open and show dashboard 

**Screenshots**
![Screenshot_20230809_110214.jpg](https://github.com/Clon1998/mobileraker/assets/56947221/7fd175c9-4708-4179-b0c4-ecd9bee0045a)

**Smartphone (please complete the following information):**
 - Device: samsung galaxy fold 5 
 - OS: android 5.1.1 
 - Browser: chrome
 - Version: 115.0.5790.166

**Mobileraker-Version: 2.4.2
This information can be found in Android's and IOS's App-Info.

**Additional context**

**Comment by cdeitrich00** [comment]
Thank you for the quick reply! This seems to be working. I will set up my printer later on when I get home from work.

**Comment by Clon1998** [comment]
Fixed in [android2.5.0](https://github.com/Clon1998/mobileraker/tree/android2.5.0)
