### ISSUE TITLE
Mesh calibration does not work. Only does first point.

### ISSUE THREAD

**Issue by GAZ082** [Clon1998/mobileraker#214]
Go to mesh calibration.
Calibrate the first point.
Hit Accept.

Boom, goes back to the mainscreen and asks to save config.

Version 2.5.0-145
Android 9

**Comment by Clon1998** [comment]
Hey,
once again. I can not reproduce that behavior. The Bed Mesh is working just fine. Also which dialog are you talking about?
Are you talking about the Bed Screw Adjust rather than Bed mesh?

**Comment by GAZ082** [comment]
Bed mesh. I'll finish a print i have now and then restart everything and try again. Will get a video if possible.

**Comment by GAZ082** [comment]
https://github.com/Clon1998/mobileraker/assets/100194/031f9b3e-7a41-42ee-908a-71239e24c030

Here @Clon1998

**Comment by Clon1998** [comment]
Ohh interesting.
I assume you are not trying to run auto bed level? Rather manual bed leveling where you adjust the offset via that dialog?

Tbh. manual bed leveling never was supported and that the dialog is shown is just a side effect of the probe/offset calibration call. I will look into this to ensure the dialog also works for manual bed leveling.

Thanks for reporting this!

**Comment by GAZ082** [comment]
Yes! Its a manual mesh.

Thanks!

**Comment by GAZ082** [comment]
Hi @Clon1998 , do you think you can do a release with the fix? Thanks!

**Comment by Clon1998** [comment]
If you're on Android, there actually is a pre release on GitHub ready to download that should include the fix.

**Comment by GAZ082** [comment]
Thank you Patrick! You are the best. It's working properly now. There is a small issue with my small screen device, if there is a lot of numbers the + button wants to leave the modal :D.

![Screenshot_20230903-154846](https://github.com/Clon1998/mobileraker/assets/100194/b78d456b-c5aa-421b-8191-72eb882ff7a3)
