### ISSUE TITLE
Does not home Z axis.

### ISSUE THREAD

**Issue by GAZ082** [Clon1998/mobileraker#215]
Hit the HOME button.
See how it homes X,Y but not Z.

Android 9
Version 2.5.0-145

**Comment by Clon1998** [comment]
Hey,

I cannot reproduce that behavior for either of the homing buttons(see video). Please provide me with a screen recording. 
Also after homing please check the GCode Console. The Buttons should issue a `G28 ` command.

https://github.com/Clon1998/mobileraker/assets/10357775/f150c30c-a461-4aeb-b961-52a173d99296

**Comment by GAZ082** [comment]
I'll do a more thorough test and get back to you.  The odd thing is, in Mainsail works ok.

**Comment by Clon1998** [comment]
Hey,
I noticed that the after my latest change the UI can be a little disconnected from the printer data if the app is reopened after being in the backg for a while.
That means I am able to send homing commands but the UI itself does not update.
Was that the thing you've experienced or did the printer itself only home one Axis?

**Comment by GAZ082** [comment]
Hey, the app is just sending

G28 XY

(The plain G28 was sent by Mainsail, the others, by your app).

![image](https://github.com/Clon1998/mobileraker/assets/100194/9a558daa-2b90-42ec-adc4-2eccb6f011f8)

**Comment by GAZ082** [comment]
Oh, I'm a moron. I've been hitting the center of the Move Axis, just like in Mainsail. I just saw that there is a "ALL" button...

Will close this.
