### ISSUE TITLE
Hide webcam if connection to stream fails

### ISSUE THREAD

**Issue by PedroC1999** [Clon1998/mobileraker#217]
**Is your feature request related to a problem? Please describe.**
I don't "always" have a webcam connected to the printer. When I don't, there is a large, unremovable warning in the dashboard webcam tile.

**Describe the solution you'd like**
A toggle in the settings that allows these errors to be suppressed and ignored, or an option to hide the webcam tile if no webcam connection is established

**Describe alternatives you've considered**
Any acceptable method of hiding this large error if no webcam is found

**Comment by non-bin** [comment]
It'd also be nice to allow you to hide the webcam all together

I use an old phone as an interface on the printer so it just takes up space

**Comment by Clon1998** [comment]
> It'd also be nice to allow you to hide the webcam all together
> 
> I use an old phone as an interface on the printer so it just takes up space

This is part of a bigger rework that will involve a customizable dashboard layout. 
All I can say is that I am working on it but there is no ETA as I am quite involved in finishing my degree right now.

**Comment by non-bin** [comment]
Awesome! We all appreciate the work you've done 👍
