### ISSUE TITLE
guideline ??

### ISSUE THREAD

**Issue by KennyBeaudoin** [Clon1998/mobileraker#223]
hello . there is actually no info here on how to make it work. could you please provide some guide lines. i managed to find a youtube video but i can only make it work on my home network. when i leave the house i no longer have access.

**Comment by Clon1998** [comment]
Please see this question in the FAQ:

https://github.com/Clon1998/mobileraker/blob/master/docs/faq.md#%EF%B8%8F-remote-printer-access

The app does not offer remote access out of the box. You will need to setup either Ocotoeverywhere, a VPN or reverse proxy.
