### ISSUE TITLE
After canceling printing, you cannot re-select the file to print

### ISSUE THREAD

**Issue by zs96500** [Clon1998/mobileraker#224]
After canceling the printing, you cannot select any file that needs to be printed to reprint, and the print button in the file is grayed out and cannot be used.

**Comment by Clon1998** [comment]
Thats new to me, could you provide me a screen recording and the logs of the app?

The logs are located at the App's setting page at the bottom

**Comment by zs96500** [comment]
[mobileraker log.zip](https://github.com/Clon1998/mobileraker/files/12387172/mobileraker.log.zip)
After canceling printing, files cannot be selected for printing.

**Comment by zs96500** [comment]
> Thats new to me, could you provide me a screen recording and the logs of the app?
> 
> The logs are located at the App's setting page at the bottom

[mobileraker log.zip](https://github.com/Clon1998/mobileraker/files/12387188/mobileraker.log.zip)
After canceling printing, files cannot be selected for printing.

**Comment by zs96500** [comment]
But it is possible to operate and print on the web page.

**Comment by Clon1998** [comment]
Found the reason. Most print buttons only work if the printer was in the standby or complete state. This issue will be fixed in the next release!
