### ISSUE TITLE
Notifications does not appear on iOS until the app is on foreground

### ISSUE THREAD

**Issue by kiwiiikiwiiikiwiii** [Clon1998/mobileraker#23]
**Describe the bug**
Notifications does not appear on iOS until the app is on foreground even the background app refresh is enabled in the iOS settings.

**To Reproduce**
1. Start print
2. Leave app in background

**Expected behavior**
Notifications should appear when the app is in the background. 

**Smartphone (please complete the following information):**
 - Device:  iPhone
 - OS: iOS 15.1
 - Version: 1.4.0.1

**Additional context**
I'd appreciate, if there was a settings to set at which percentages the notification should appear.

**Comment by edddeduck** [comment]
Reproduced using TestFlight 1.4.1 (1.4.1.0)

- iPhone 12 Pro Max
- iOS 15.3
