### ISSUE TITLE
Documentation doesn't clarify licensing

### ISSUE THREAD

**Issue by Jookia** [Clon1998/mobileraker#231]
The README and website list the project as free and open source, which are terms used to refer to software under an OSI-approved or FSF-approved open source license. This is not the case for this project.

Additionally no where in the documentation does it state this this software cannot be used for commercial use. It is quite possible people are violating this license unknowingly.

Changing the documentation be clear and unambiguous that this software is freeware and only usable for non-commercial use would solve this issue.

**Comment by Clon1998** [comment]
> The README and website list the project as free and open source, which are terms used to refer to software under an OSI-approved or FSF-approved open source license. This is not the case for this project.
> 
> 
> 
> Additionally no where in the documentation does it state this this software cannot be used for commercial use. It is quite possible people are violating this license unknowingly.
> 
> 
> 
> Changing the documentation be clear and unambiguous that this software is freeware and only usable for non-commercial use would solve this issue.

I agree that I might need to update some claims on the project's website.
However, I want to make clear that the app core codebase is still open source. I also partly disagree with your concern that the readme does not State anything about the license. The repository itself contains a license file which clearly states that. However, for clarity I can change the readme in this direction.

**Comment by Jookia** [comment]
On Thu, Aug 24, 2023 at 12:19:42AM -0700, Patrick Schmidt wrote:
> I agree that I might need to update some claims on the project's website.
> However, I want to make clear that the app core codebase is still open source. I also partly disagree with your concern that the readme does not State anything about the license. The repository itself contains a license file which clearly states that. However, for clarity I can change the readme in this direction.

Saying it's open source is a little misleading as it doesn't fit the open source definition: https://opensource.org/osd/
If you mean 'source available' then that is more accurate. But it isn't open source.

**Comment by Clon1998** [comment]
@Jookia I adjusted the readme in #232.
