### ISSUE TITLE
Add custom layer height notifications

### ISSUE THREAD

**Issue by TomW1605** [Clon1998/mobileraker#235]
### Problem Description
there is often a layer that you want to watch being printed to make sure it goes down ok and it can be annoying to sit there waiting for it.

### Proposed Solution
it would be really helpful to be able to setup notifications for a specific layer (probably 2-3 layers before the one you want to watch)

### Alternatives Considered
sitting there and waiting for it
or adding custom Gcode to that layer in the slicer but that is easy to forget and you cant do it mid print

### Additional Context
this is something i used all the time with OctoPod on my last printer

---

**Checklist**
To help us understand your feature request, please ensure you've covered the following points:
- [x] Provided a clear description of the problem you're facing.
- [x] Clearly outlined the proposed solution or feature.
- [x] Mentioned any alternative solutions or ideas you've considered.
- [x] Included any relevant context or supporting materials.

Your input is valuable in shaping the development of our project. Thank you for taking the time to submit your feature request!

**Comment by Clon1998** [comment]
Closed as not planned.
See my answer here:
https://github.com/Clon1998/mobileraker/issues/356#issuecomment-2050506923
