### ISSUE TITLE
Remote webcam not working

### ISSUE THREAD

**Issue by joschiv1977** [Clon1998/mobileraker#239]
After setting the alternative remote connection, everything works, except the Remote Webcam i setup. 

My VPN connection (Tailscale) works without any problems. I can connect to the webcam URL via Mobile Safari on my iPhone. But with Mobileraker it shows only a gray pic. 

### Version Information
- Mobileraker: 2.5.4-258 TestFlight Version
- Klipper: v0.11.0-271-g5f990f93
- Moonraker: v0.8.0-138-gfe120952

### Debug Logs
💡 Completed FirebaseRemote init
💡 Machine in box is Ender 3 v2 (XXXXXXXXXXXXXXX)#936062536
💡 Completed Hive init
💡 Completed PaymentService init
💡 Selecting machine Ender 3 v2
💡 Received fetchAll
💡 Got customerInfo: CustomerInfo(XXXX
💡 RCat ID: $RCAnonymousID:XXXXXXXXXXXXXXX
💡 Received isSupporter true
💡 Max allowed machines for non Supporters is -1
💡 Completed initialRoute init
💡 Started initializeAvailableMachines
💡 Received all machines
💡 machineProvider creation STARTED XXXXXXX568a7889
💡 machineProvider creation DONE XXXXXXXXXX4568a7889
💡 initialized all machineProviders
💡 Completed initializeAvailableMachines
💡 Notifications are permitted: true
💡 Setup notification channels
💡 Setup ReceiverPort!
💡 Completed NotificationService init
💡 Theme selected: 0, available theme len: 5
💡 A manual-RemoteClient is available. Can do handover in case local client fails! ref:XXXXXXXXXXX
💡 [ClientType.local@ws://XXX.XXX.XXX.XXX/websocket #618905507] JsonRpcClient CREATED!!
💡 [ClientType.local@ws://XXX.XXX.XXX.XXX/websocket #618905507] Trying to connect
💡 [ClientType.local@ws://XXX.XXX.XXX.XXX/websocket #618905507] ClientState.disconnected ➝ ClientState.connecting
💡 [ClientType.local@ws://XXX.XXX.XXX.XXX/websocket #618905507] Using headers {X-Api-Key: XXXXXXXXXXXX}
💡 [ClientType.local@ws://XXX.XXX.XXX.XXX/websocket #618905507] Using timeout 0:00:03.000000
💡 Returning LocalClient
💡 Printer Service received klippyState: null
PlatformException(FCM_EXCEPTION, The operation couldn’t be completed. Underlying error: bad URL, awesomeFcmException.FcmException.request.token, null)
#0   StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:652)
#1   MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:310)
#2   <asynchronous suspension>
#3   AwesomeNotificationsFcm.requestFirebaseAppToken (package:awesome_notifications_fcm/src/awesome_notifications_fcm_core.dart:127)
#4   <asynchronous suspension>
#5   FutureHandlerProviderElementMixin.handleFuture.<anonymous closure>.<anonymous closure> (package:riverpod/src/async_notifier/base.dart:337)
#6   <asynchronous suspension>
⛔ Error while trying to register supporter status/fcm token in firebase:
💡 App forgrounded
⚠️ [ClientType.local@ws://XXX.XXX.XXX.XXX/websocket #618905507] Got channel error SocketException: HTTP connection timed out after 0:00:03.000000, host: XXX.XXX.XXX.XXX, port: 80
⛔ [ClientType.local@ws://XXX.XXX.XXX.XXX/websocket #618905507] WS-Stream error: SocketException: HTTP connection timed out after 0:00:03.000000, host: XXX.XXX.XXX.XXX, port: 80
💡 [ClientType.local@ws://XXX.XXX.XXX.XXX/websocket #618905507] ClientState.connecting ➝ ClientState.error
💡 Local clientState is ClientState.error. Will switch to octo remoteClient. ref:361960451
⚠️ Returned manual-RemoteClient
💡 Printer Service received klippyState: KlipperState.error
💡 [ClientType.manual@ws://XXXXXXXXwebsocket? #760326630] JsonRpcClient CREATED!!
💡 [ClientType.manual@ws://XXXXXXXX/websocket? #760326630] Trying to connect
💡 [ClientType.manual@ws://XXXXXXXX/websocket? #760326630] ClientState.disconnected ➝ ClientState.connecting
💡 [ClientType.manual@ws://XXXXXXXX/websocket? #760326630] Using headers {X-Api-Key: XXXXXXXXXXX}
💡 [ClientType.manual@ws://XXXXXXXX/websocket? #760326630] Using timeout 0:00:10.000000
💡 Printer Service received klippyState: KlipperState.error
💡 [ClientType.local@ws://XXX.XXX.XXX.XXX/websocket #618905507] JsonRpcClient disposed!
💡 [ClientType.manual@ws://XXXXXXXX/websocket? #760326630] ClientState.connecting ➝ ClientState.connected
💡 >>>Fetching Server.Info
💡 >>>Fetching Printer.Info
💡 Queue status request...
💡 <<<Received Server.Info
💡 Printer Service received klippyState: KlipperState.ready
💡 Refreshing printer for uuid: XXXXX
💡 >>>Querying printers object list
💡 Getting settings
💡 <<<Received Printer.Info
💡 Partial Update STARTED KlipperInstance(klippyConnected: true, klippyState: KlipperState.ready, components: [klippy_connection, application, websockets, internal_transport, dbus_manager, database, file_manager, klippy_apis, secrets, template, shell_command, machine, data_store, proc_stats, job_state, job_queue, http_client, announcements, webcam, extensions, spoolman, timelapse, power, authorization, history, update_manager], warnings: [], klippyStateMessage: null)
💡 Partial Update Done KlipperInstance(klippyConnected: true, klippyState: KlipperState.ready, components: [klippy_connection, application, websockets, internal_transport, dbus_manager, database, file_manager, klippy_apis, secrets, template, shell_command, machine, data_store, proc_stats, job_state, job_queue, http_client, announcements, webcam, extensions, spoolman, timelapse, power, authorization, history, update_manager], warnings: [], klippyStateMessage: Printer is ready)
⚠️ watchWhere just forces owner to invalidate! Ref:AutoDisposeFutureProviderElement<MachineSettings>(provider: selectedMachineSettingsProvider:AutoDisposeFutureProvider<MachineSettings>#0946a, origin: selectedMachineSettingsProvider:AutoDisposeFutureProvider<MachineSettings>#0946a)
💡 Getting settings
💡 <<<Received printer objects list!
💡 >>>Querying Printer Objects!
💡 <<<Received queried printer objects
💡 Fetching cached temperature store data
💡 Received cached temperature store for [temperature_sensor raspberry_pi, temperature_sensor mcu_temp, heater_bed, extruder]
💡 Subscribing printer objects for ws-updates!
💡 Updating Default Macros for "Ender 3 v2(ws://XXX.XXX.XXX.XXX/websocket)"!
💡 Getting settings
💡 Also requesting an update for current_file: XXXXXXXX.gcode
💡 Getting meta for file: `XXXXXXXXXXX.gcode`
💡 Max allowed machines for non Supporters is -1
💡 List Webcams request...
💡 Trying to fetch all webcams from moonraker.
💡 UPDATED current_file: GCodeFile(nXXXXXXXXXXXX)])
💡 Received 2 webcams from moonraker.
💡 Got 2 webcams
💡 App in AppLifecycleState.inactive
💡 App forgrounded
💡 Getting fcm.client
💡 Show Dialog request for DialogType.logging

### Additional Context
Add any other relevant context about the problem here.
![IMG_0342](https://github.com/Clon1998/mobileraker/assets/139355048/b5449c5e-a600-4525-8d16-4a68f9d26628)

**Comment by Clon1998** [comment]
Is the cam a webrtc or Mjpeg one?

**Comment by joschiv1977** [comment]
It's MjpegStreamerAdaptive. Tried all of them. None works.

**Comment by Clon1998** [comment]
> It's MjpegStreamerAdaptive. Tried all of them. None works.

Thanks!
I will have a look. Seems like I never actually added the manual-rempte connection code for the webcams 🫠.

**Comment by Clon1998** [comment]
8d312618c75cc1d5c8ef58bc3d1e98dd9b1e921d should fix that.

Currently building a new test flight version.

Please let me know if it is working now :).

Note, that WebRtc might not be working yet since it requires some other magic/an update to crownsnest :).

**Comment by joschiv1977** [comment]
perfect. It’s working now. Thank you for your fast support
