### ISSUE TITLE
iOS Monthly Supporter subscription

### ISSUE THREAD

**Issue by joschiv1977** [Clon1998/mobileraker#240]
Version 2.5.4-259 TestFlight

is it intentional? or a bug ;-)

<img src="https://github.com/Clon1998/mobileraker/assets/139355048/3bb5d3a7-bfa9-412a-82ba-f137bb92cdfa" width="616" height="473">

**Comment by Clon1998** [comment]
Hey,
that is not a bug at all. It is the intended behavior of [Apple's TestFlight](https://developer.apple.com/in-app-purchase/#:~:text=In%E2%80%91app%20purchases%20in%20TestFlight,can%20submit%20them%20for%20review.):

> In‑app purchases in TestFlight use the sandbox environment, so they're free to testers and don't carry over into production once your app is released on the App Store.

It (should) not transfer over to the regular app version :).
