### ISSUE TITLE
Moonraker Timelapse Support

### ISSUE THREAD

**Issue by fuzelet** [Clon1998/mobileraker#241]
### Problem Description
I am someone that uses Moonraker Timelapse on prints.  This feature comes in handy when looking at issues with prints or to share with people.  Currently I do not see a way to change folders or access the timelapse folder/section.

### Proposed Solution
Add a section to the application called Timelapse that would point to the timelapse folder.
AND/OR
Allow the "Files" section to change folders to various other folders such as logs, config, timelapse, etc.

### Alternatives Considered
Login to printer website and access the timelapse videos that way.

### Additional Context
https://github.com/mainsail-crew/moonraker-timelapse
https://github.com/mainsail-crew/moonraker-timelapse/blob/main/docs/installation.md
https://github.com/mainsail-crew/moonraker-timelapse/blob/main/docs/configuration.md

![Screenshot_20230830-111247_Cromite](https://github.com/Clon1998/mobileraker/assets/70331495/46db44f0-7a8e-4677-a661-734ceaa4cda4)
![Screenshot_20230830-111251_Cromite](https://github.com/Clon1998/mobileraker/assets/70331495/abc32455-b237-4d0c-845d-751f4b6a70f4)

**Comment by Clon1998** [comment]
Hey,
what kind of files are stored in the dir (Video format)?

**Comment by fuzelet** [comment]
> Hey, what kind of files are stored in the dir (Video format)?

I am seeing .mp4 files in the folder I have.

**Comment by fuzelet** [comment]
Appreciate the quick turn around on this! Can't believe it's already in the application. Wanted to report back that the folder shows an additional .jpg file for each mp4 that when opened just constantly shows a download screen.

Not a big deal but wanted to report it back either way just in case you weren't aware.

![Screenshot_20230906-184436_Mobileraker](https://github.com/Clon1998/mobileraker/assets/70331495/d23e5ab0-f76d-44e7-b942-fe351a41eeb5)
![Screenshot_20230906-184431_Mobileraker](https://github.com/Clon1998/mobileraker/assets/70331495/7d106334-ae2a-4f57-b5f1-82b2ac6d40fe)

**Comment by Clon1998** [comment]
Thanks,
i was not sure what files to expect. Therefore no logic is in place to open up a jpeg.

Should be a easy fix though

**Comment by fuzelet** [comment]
> Thanks, i was not sure what files to expect. Therefore no logic is in place to open up a jpeg.
> 
> Should be a easy fix though

Sorry for the inconvenience. I wasn't aware there was any other files in that directory as the mainsail gui doesn't show anything but the .MP4 files.

**Comment by Clon1998** [comment]
> > Thanks, i was not sure what files to expect. Therefore no logic is in place to open up a jpeg.
> 
> > 
> 
> > Should be a easy fix though
> 
> 
> 
> Sorry for the inconvenience. I wasn't aware there was any other files in that directory as the mainsail gui doesn't show anything but the .MP4 files.

I thought I was doing the same 🙃
I will verify that later today.

**Comment by Clon1998** [comment]
Adjusted in 2.6.3
