### ISSUE TITLE
Grey screen after File selection

### ISSUE THREAD

**Issue by DrFate09** [Clon1998/mobileraker#246]
### Description
After tapping a GCODE file to open up and try to print, the screen turns to grey. 

### Steps to Reproduce
1. Go to Files
2. Click on a GOCDE file
3. See the grey screen

### Screenshots
![Screenshot_20230906-133944](https://github.com/Clon1998/mobileraker/assets/22684695/4b0b499f-f3af-40cb-81d4-a5366993ce55)

### Version Information
- Mobileraker: 2.6.0

**Comment by Clon1998** [comment]
Thanks will trigger a hotfix right away.

**Comment by Clon1998** [comment]
Fix should be rolling out
