### ISSUE TITLE
Possible memory leak in mobileraker.py

### ISSUE THREAD

**Issue by austinrdennis** [Clon1998/mobileraker#251]
### Description
I've noticed a slow and gradual increase in the amount of memory mobileraker.py uses that points to a possible memory leak.

### Steps to Reproduce
Boot the host machine and start the mobileraker service. Not sure what exactly the mechanism is.

### Expected Behavior
Memory usage remains relatively stable over time and is reasonable.

### Screenshots
![SCR-20230909-ntbp](https://github.com/Clon1998/mobileraker/assets/88241004/2d6a7548-2bd7-4a90-9f44-301ece286498)
![SCR-20230909-nuls](https://github.com/Clon1998/mobileraker/assets/88241004/f4d5172c-f10c-4464-8d7b-ef80cb71529f)

### Version Information
- Mobileraker: v0.4.0-25-g2808855d (host) 2.5.2-246 (iOS client)
- Klipper: v0.11.0-271-g5f990f93
- Moonraker: v0.8.0-138-gfe120952

### Debug Logs
[mobileraker_2023-09-08T21-06-33.log](https://github.com/Clon1998/mobileraker/files/12566802/mobileraker_2023-09-08T21-06-33.log)
[mobileraker.log](https://github.com/Clon1998/mobileraker/files/12566818/mobileraker.log)

### Additional Context
After about 26 hours of runtime, it's now using around 2.1 GB of system memory which seems like way too much.

---

#### Checklist
To help us diagnose the issue, please ensure you've completed the following steps:
- [X] Provided a clear bug description.
- [X] Listed detailed steps to reproduce the issue.
- [X] Described the expected behavior.
- [X] Included the Mobileraker version you are using.
- [X] Attached Mobileraker's debug log files.
- [X] Specified the version numbers of Klipper and Moonraker if applicable.

**Comment by austinrdennis** [comment]
I've also posted this as bug in the mobileraker_companion repo as issue 57 as I wasn't sure which one to choose. Feel free to close this issue if it's not applicable this repo.

**Comment by austinrdennis** [comment]
`sudo systemctl restart mobileraker.service` clears out the memory usage at least temporarily. I'll see if it builds up again.

**Comment by Clon1998** [comment]
'll leave this open since other users might start to look for the issue on mobileraker rather than the mobileraker_companion repo.

The original issue for this problem is https://github.com/Clon1998/mobileraker_companion/issues/27

**Comment by austinrdennis** [comment]
> 'll leave this open since other users might start to look for the issue on mobileraker rather than the mobileraker_companion repo.
> 
> The original issue for this problem is [Clon1998/mobileraker_companion#27](https://github.com/Clon1998/mobileraker_companion/issues/27)

Doh! I feel like a total dork for not looking for a duplicate issue in the other repo, only this one. My bad! I'll report back if the issue is solved for me sometime on Monday. I got a long print going, can't update just yet.

**Comment by austinrdennis** [comment]
Looks like the latest commit on mobileraker_companion squashed this bug. Thanks for all your awesome work! 😁
