### ISSUE TITLE
Multiple Printers - File view not updating correctly between printers

### ISSUE THREAD

**Issue by fuzelet** [Clon1998/mobileraker#253]
### Description
Open printer.cfg on one printer then switch to another printer and open that printer.cfg. The second printer's file is actually the first. The file being viewed is actually from a printer that is "off" as well.

### Steps to Reproduce
1. Go to 'Files'
2. Click on 'printer.cfg'
3. Close file, save, etc 
4. Change to another printer that is running.
5. Repeat steps above.
6. File opener second time is actually file from other printer.

### Expected Behavior
File being opened is actually the proper file from the respective printer.

### Screenshots
![Screenshot_20230911-185809_Mobileraker](https://github.com/Clon1998/mobileraker/assets/70331495/d1e6926c-8828-4d31-b106-4702102126e0)
![Screenshot_20230911-185806_Mobileraker](https://github.com/Clon1998/mobileraker/assets/70331495/8149970d-a8df-468f-9650-c6c65a8cb16b)
![Screenshot_20230911-185839_Firefox Beta](https://github.com/Clon1998/mobileraker/assets/70331495/4abd99e7-ed2f-4b53-abf1-52dcbd2466ae)
![Screenshot_20230911-185936_Mobileraker](https://github.com/Clon1998/mobileraker/assets/70331495/29bca935-51c1-4b3b-aebd-5b791f6100e6)
![Screenshot_20230911-185812_Mobileraker](https://github.com/Clon1998/mobileraker/assets/70331495/735913b7-73d8-4bff-ab83-87916bee495b)

### Version Information
- Mobileraker: [v2.6.2-276 - android]
- Klipper: [v0.11.0-275-g8ef0f7d7]
- Moonraker: [0.8.0-138-gfe120952]

### Debug Logs
[mobilerakerapplogs.zip](https://github.com/Clon1998/mobileraker/files/12580952/mobilerakerapplogs.zip)

---

#### Checklist
To help us diagnose the issue, please ensure you've completed the following steps:
- [x] Provided a clear bug description.
- [x] Listed detailed steps to reproduce the issue.
- [x] Described the expected behavior.
- [x] Included the Mobileraker version you are using.
- [x] Attached Mobileraker's debug log files.
- [x] Specified the version numbers of Klipper and Moonraker if applicable.

**Comment by fuzelet** [comment]
> Hey! Thanks for reporting this. I need to double check but I think I already fixed that! The fix will be included in 2.6.3

Appreciate the quick response as always. Let me know if you need anything else from me.

**Comment by fuzelet** [comment]
Wanted to post this here as well in the event it's related for some reason. If not I can open a new issue for it.

I noticed that the information in the "print preview" is not updating correctly and not sure if it will lead to issues with preheating, etc. The hotend and bed temps are flipped?
The thumbnail of the print is also pixelated even with a 32x32 and 400x400 thumbnail.

![Screenshot_20230912-125655_Firefox Beta](https://github.com/Clon1998/mobileraker/assets/70331495/feabeeaa-2f52-4819-a375-6d2f3144d49b)
![Screenshot_20230912-125711_Mobileraker](https://github.com/Clon1998/mobileraker/assets/70331495/572ead61-2988-456e-b894-e5a7ebb588fa)

**Comment by Clon1998** [comment]
> In the future should I try the TestFlight iOS version prior to reporting issues? I primarily use Beta Android as I am a supporter on that platform, but can always give the iOS TestFlight version a go PRIOR to reporting an issues. I ask I see the iOS version is typically "newer" than the android equivalent? I'd rather limit the amount of extra work you do cause I am just using an older version of the application. Is there a better place to bring these questions up as well for development purposes? Discord? Discussion Thread?
> 
> Not sure if this issue is even related to the above, just want to make sure I am not reporting duplicates or stuff that was already fixed in a newer version, etc.

No that's fine,
also I just checked. 023d4471ea7eb2abb4ccd30b8982ccda9549f322 Fixed the downloading of config files :).

**Comment by Clon1998** [comment]
Included in 2.6.3

**Comment by fuzelet** [comment]
Not sure if this warrants a new issue or not, but noticed the same issue with gcode file thumbnails not syncing now.

![Screenshot_20230919-164032_Firefox Beta](https://github.com/Clon1998/mobileraker/assets/70331495/38aefab2-2d01-4358-b4f5-fde85415a0d9)
![Screenshot_20230919-164258_Mobileraker](https://github.com/Clon1998/mobileraker/assets/70331495/57b08699-e971-44a5-aa27-bd826e419d07)
