### ISSUE TITLE
Progress  percentage not the same with mainsail

### ISSUE THREAD

**Issue by jpbnto** [Clon1998/mobileraker#261]
### Description
Progress percentage is not the same with mainsail.
It was working before i uodated mobileraker.

### Steps to Reproduce
4. See the error.

### Expected Behavior
Is should be the same.

### Screenshots
![Screenshot_2023-09-23-09-48-21-121_com android chrome](https://github.com/Clon1998/mobileraker/assets/91659388/e5df0aee-e21f-4809-9797-a78661e17ce5)
![Screenshot_2023-09-23-09-48-17-573_com mobileraker android](https://github.com/Clon1998/mobileraker/assets/91659388/28e9532d-312b-45c3-9dfe-3bfa5f95811a)

### Version Information
- Mobileraker: v0.4.0-27-g21e70b33
- Klipper: v0.11.0-276-ge9bf2d4c
- Moonraker: v0.8.0-139-g3d9052d7

### Debug Logs
Please attach the log files generated by Mobileraker. You can find them by navigating to the app's settings page, scrolling to the bottom, and pressing the `Debug Logs` button.

### Additional Context
Add any other relevant context about the problem here.

---

#### Checklist
To help us diagnose the issue, please ensure you've completed the following steps:
- [ ] Provided a clear bug description.
- [ ] Listed detailed steps to reproduce the issue.
- [ ] Described the expected behavior.
- [ ] Included the Mobileraker version you are using.
- [ ] Attached Mobileraker's debug log files.
- [ ] Specified the version numbers of Klipper and Moonraker if applicable.

**Comment by Clon1998** [comment]
Hey,
I will look i to this but I suspect that the app got stuck.
Did you try to refresh the page in the app or force close and reopen the app?

**Comment by jpbnto** [comment]
Unfortunately i didn't try that. I just saw the notifications then i compared the app and mainsail. 

I will try it when i will print again.

**Comment by jpbnto** [comment]
That's weird. They are now the same. 

![Screenshot_2023-09-24-16-10-25-828_com android chrome](https://github.com/Clon1998/mobileraker/assets/91659388/d39522dd-a8a9-4305-9e6e-4830f809379e)
![Screenshot_2023-09-24-16-10-29-603_com mobileraker android](https://github.com/Clon1998/mobileraker/assets/91659388/e09ecaf6-22fc-4863-8cf4-2cf611877b38)

**Comment by jpbnto** [comment]
Another gcode 1% difference
![Screenshot_2023-09-25-08-19-14-494_com android chrome](https://github.com/Clon1998/mobileraker/assets/91659388/e0df152c-b05a-477e-bcd9-9f98c91fcb3a)
![Screenshot_2023-09-25-08-19-10-970_com mobileraker android](https://github.com/Clon1998/mobileraker/assets/91659388/2f8f1dc7-c8d6-4c5b-af4e-26b1a51e6ff8)

**Comment by Clon1998** [comment]
> Another gcode 1% difference ![Screenshot_2023-09-25-08-19-14-494_com android chrome](https://user-images.githubusercontent.com/91659388/270200925-e0df152c-b05a-477e-bcd9-9f98c91fcb3a.jpg) ![Screenshot_2023-09-25-08-19-10-970_com mobileraker android](https://user-images.githubusercontent.com/91659388/270200936-2f8f1dc7-c8d6-4c5b-af4e-26b1a51e6ff8.jpg)

Sorry about my late response.

1% is good. It can happen that due to precision error, there is a small deviation between the two UIs.
