### ISSUE TITLE
JRpcTimeoutError

### ISSUE THREAD

**Issue by siboj** [Clon1998/mobileraker#263]
I try to use zerotier tunnel from my mobile to my printer and sometime works sometimes no, error  that i recive from mobileraker is 

Exception:
 JRpcTimeoutError: JRpcMethod timed out after 0:00:10.000000

#0      JsonRpcClient.sendJRpcMethod.<anonymous closure> (package:common/network/json_rpc_client.dart:226)
#1      FutureExtensions.onError.onError (dart:async/future.dart:1069)
#2      _RootZone.runBinary (dart:async/zone.dart:1666)
#3      _FutureListener.handleError (dart:async/future_impl.dart:171)
#4      Future._propagateToListeners.handleError (dart:async/future_impl.dart:852)
#5      Future._propagateToListeners (dart:async/future_impl.dart:873)
#6      Future._completeError (dart:async/future_impl.dart:649)
#7      Future.timeout.<anonymous closure> (dart:async/future_impl.dart:927)
#8      Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:18)
#9      _Timer._runTimers (dart:isolate-patch/timer_impl.dart:398)
#10     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:429)
#11     _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:189)

I change timeout to 30 s but still same error

**Comment by Clon1998** [comment]
This indicates that the printer does not answer in time. The next time this happens, could you verify if mainsail/fluidd is also broken?

**Comment by siboj** [comment]
> This indicates that the printer does not answer in time. The next time this happens, could you verify if mainsail/fluidd is also broken?

Its not broken everithing works fine but i don't know why need tooì much time to open

**Comment by siboj** [comment]
If i waiting in open app he will connect, he will try a lot of time and it will pass
![Screenshot_20231003_144957](https://github.com/Clon1998/mobileraker/assets/94691807/ffaa0693-fd17-4834-ac59-ddd108e54758)

**Comment by TaylorN15** [comment]
You could try increasing the value in Printer Settings -> Client timeout in the app.

**Comment by siboj** [comment]
> You could try increasing the value in Printer Settings -> Client timeout in the app.

I try that first but still same

**Comment by Clon1998** [comment]
> > You could try increasing the value in Printer Settings -> Client timeout in the app.
> 
> I try that first but still same

I am looking into that.
It seems like I made the app throw `JRpcTimeoutError `  to aggressively. I already adjusted it in some places for the upcoming release. Lets see if that helps :)

**Comment by siboj** [comment]
> > > You could try increasing the value in Printer Settings -> Client timeout in the app.
> > 
> > 
> > I try that first but still same
> 
> I am looking into that. It seems like I made the app throw `JRpcTimeoutError ` to aggressively. I already adjusted it in some places for the upcoming release. Lets see if that helps :)

Thanks man

I would like to test new version

**Comment by siboj** [comment]
Hi

I tested new version of app and everithing is fine, its working very well
