### ISSUE TITLE
Two finger swipe to switch between printers. 

### ISSUE THREAD

**Issue by simpat1zq** [Clon1998/mobileraker#27]
I think it would be nice to have a quicker way to switch between printers. Since there are modules in there that use the one finger swipe, I think implementing a two finger swipe would be awesome to quickly go between printers.

**Comment by falo2k** [comment]
Either a gesture or a single swipe on the printer name would also work IMO.

**Comment by Clon1998** [comment]
Added in 99afe496db51be67a19ebf6ea60993f53566e083
