### ISSUE TITLE
Live Activity takes up too much space in the Dynamic Island

### ISSUE THREAD

**Issue by CobreDev** [Clon1998/mobileraker#273]
### Description
When the Live Activity is active, it takes the entire width of my status bar. This makes viewing the time or other status bar info very hard 

### Steps to Reproduce
1. Start Live Activity by exiting the app
2. Observe

### Expected Behavior
There should be less blank space between the Island, the countdown, and the circle graph to allow the time and other info to be visible

### Screenshots
![image](https://github.com/Clon1998/mobileraker/assets/36574329/a233fe77-38dc-4659-b20c-24b6e0041f81)
![image](https://github.com/Clon1998/mobileraker/assets/36574329/2aab19cb-3a0f-4a6d-981e-29e8f0f67cc1)

### Version Information
- Mobileraker: 2.6.4

### Debug Logs
N/A

### Additional Context
Device - iPhone 15 Pro, iOS 17.0.3

---

#### Checklist
To help us diagnose the issue, please ensure you've completed the following steps:
- [X] Provided a clear bug description.
- [X] Listed detailed steps to reproduce the issue.
- [X] Described the expected behavior.
- [X] Included the Mobileraker version you are using.
- N/A Attached Mobileraker's debug log files.
- N/A Specified the version numbers of Klipper and Moonraker if applicable.

**Comment by Clon1998** [comment]
Hey,
I've also noticed that on the emulator and pushed a fix for that . It will be included in the next release alongside some other changes to the live activity.

**Comment by CobreDev** [comment]
Fantastic, thank you!

**Comment by Clon1998** [comment]
Here is the updated size, sadly due to a bug with the ActivityKit this is the best I can do

<img width="388" alt="image" src="https://github.com/Clon1998/mobileraker/assets/10357775/a7185ab0-1c9e-4072-80ba-1cacb9ef25b7">

**Comment by CobreDev** [comment]
That's not bad!

**Comment by jordanborth** [comment]
It's the timer taking up the whole view right?

**Comment by Clon1998** [comment]
If I remember it correctly, the timer would expand the live activity to its maximum size.
