### ISSUE TITLE
Webcam : erreur 404

### ISSUE THREAD

**Issue by mick69000** [Clon1998/mobileraker#283]
### Description
imossible de connecter la webcam

### Description
J'ai une erreur 404 au niveau de la webcam

### Expected Behavior
affichage de la webcam

### Screenshots
![IMG_020B2DB8B276-1](https://github.com/Clon1998/mobileraker/assets/149667730/0ef7e6a2-b760-4745-a4ba-7471db49349e)
![IMG_890370198246-1](https://github.com/Clon1998/mobileraker/assets/149667730/3473e6fb-c3af-4fee-adc1-d421e4d144ca)

### Version Information

- Device-OS (iOS): [iOS 17.1.1]
- Mobileraker: mobile=> [2.6.6-234] klipper =>[v0.4.0-29-g5a4cae4a]
- Klipper: [v0.11.0-311-g9e765dae]
- Moonraker: [v0.8.0-197-g975011d1]

### Debug Logs

[mobileraker_2023-11-12T19-03-04.log](https://github.com/Clon1998/mobileraker/files/13339720/mobileraker_2023-11-12T19-03-04.log)

### Additional Context
Système installé sur un mini pc (Ubuntu 23.04 lunar).
Je passe par un nom de domaine ( elf.mickahome.fr)

**Comment by Clon1998** [comment]
I don't speak nor understand a single line of French.
However, judging by your screenshots the webcam you configured is not pointing to the correct endpoint.
You can either define a webcam via its relative URI (To the printer address) or use an absolut URI (E.g. `http://my-cool-printer-cam.io/some/path?alsoAQuery`).

Without more details about the webcam config inside mobileraker and also the configs on your host system, I can not do much.

**Comment by rumym** [comment]
Looks related to the bug I just filed - https://github.com/Clon1998/mobileraker/issues/299

**Comment by Clon1998** [comment]
> Looks related to the bug I just filed - #299

Not quite; on this issue, the webcam was not found. Most likely, the cam is pointing to the wrong URL.
In #299 you are having an SSL issue.

**Comment by rumym** [comment]
I am not using SSL when connecting to local. I have attached the
configuration in the app as well as the error I am getting.

**Comment by Clon1998** [comment]
Closed due to inactivity for two months. Feel free to reopen if additional information is provided.
