### ISSUE TITLE
Spoolman Page error

### ISSUE THREAD

**Issue by Clon1998** [Clon1998/mobileraker#285]
I made a mistake by including the Spoolman menu entry in version 2.6.7 of the app when it was not expected to have Spoolman support yet. 
As a result, users might encounter an error when trying to access the Spoolman page. 

This issue acts as a known bug for the benefit of other users who might report the Spoolman page not working.

**Comment by PatrickGlatz** [comment]
shit, saw it to late ^^, have commented on the #245

**Comment by Clon1998** [comment]
2.6.8 will be rolling out slowly. For now, it removed the Spoolman page until I get some feedback in regards to the UI that is required.
