### ISSUE TITLE
Optimise for landscape orientation

### ISSUE THREAD

**Issue by NeighNeighNeigh** [Clon1998/mobileraker#290]
### Problem Description
The UI is okay for portrait, but not great for landscape. Needing to scroll to find buttons feels a bit clumsy and unreliable.

### Proposed Solution
Redesign the layout under landscape mode, making better use of the available space. 

Further, it would great if landscape mode would display full screens of each section, without the need for vertical scrolling. This would behave more like a touch screen interface on the printer. Each area would be its own page rather than a long scrolling 'one pager'. Now buttons would be in repeatable and predictable locations, where muscle memory can access them- rather than being just "somewhere" depending on how far you have scrolled.

This would make the experience much better IMO.

### Alternatives Considered
JS / CSS hacking the mainsail / fluid web ui

### Additional Context
Here is as screen recording where you can see landscape mode is a bit messy

https://github.com/Clon1998/mobileraker/assets/4795315/d1dcc9ef-753f-4825-99fa-15891007f599

---

**Checklist**
To help us understand your feature request, please ensure you've covered the following points:
- [ ✓ ] Provided a clear description of the problem you're facing.
- [ ✓ ] Clearly outlined the proposed solution or feature.
- [ ✓ ] Mentioned any alternative solutions or ideas you've considered.
- [ ✓ ] Included any relevant context or supporting materials.

Your input is valuable in shaping the development of our project. Thank you for taking the time to submit your feature request!

**Comment by Clon1998** [comment]
Implement in 2.7.0.
Added support for tablet/medium sized screens/layouts.
