### ISSUE TITLE
mobileraker_pro

### ISSUE THREAD

**Issue by jmwhelan** [Clon1998/mobileraker#293]
### Problem Description
Can't contribute to project, missing mobileraker_pro dependency.

### Proposed Solution
Please include the missing dependency.

### Alternatives Considered### Additional Context

---

**Checklist**
To help us understand your feature request, please ensure you've covered the following points:
- [x] Provided a clear description of the problem you're facing.
- [x] Clearly outlined the proposed solution or feature.
- [x] Mentioned any alternative solutions or ideas you've considered.
- [x] Included any relevant context or supporting materials.

Your input is valuable in shaping the development of our project. Thank you for taking the time to submit your feature request!

**Comment by Clon1998** [comment]
Hey,
I just uploaded a striped-down version of the pro lib.
Have a look at my updated [contribute section](https://github.com/Clon1998/mobileraker?tab=readme-ov-file#environment-setup-for-contribution) in the readme.
