### ISSUE TITLE
Status text seems wrong about moonraker

### ISSUE THREAD

**Issue by nathanielhudson** [Clon1998/mobileraker#30]
**Describe the bug**
The status text you get by holding the status icon seems to be wrong as far as I can tell. Text says “moonraker disconnected to klipper”, but I believe that logic is reversed and moonraker is in fact connected to klipper. 

**To Reproduce**
1. Hold the status icon when connected to a printer

**Expected behavior**
Text to correctly reflect the state of the connection. 

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: iPhone8

**Mobileraker-Version
I’m not sure where to find this info. 

**Screenshot
![517B8796-AEAC-4AD6-A7D0-0666C9967CFC](https://user-images.githubusercontent.com/2744848/147859228-2f4d1818-d8a6-4cfc-aaa0-a52e9f60762f.png)

**Comment by Clon1998** [comment]
That's correct.
The tooltip should show the server state (Moonraker) alongside the klippy connection.
I fixed that but don't know the commit hash rn.
