### ISSUE TITLE
ETA label wrong

### ISSUE THREAD

**Issue by mlee12382** [Clon1998/mobileraker#300]
### Description

The label ETA fieldsays "Filament"

### Expected Behavior
ETA field should be labeled ETA

### Screenshots
![Screenshot_20231217_080852.jpg](https://github.com/Clon1998/mobileraker/assets/89716126/e7cd0b18-2703-41a5-9507-8854b6a911d3)

### Version Information

- Device-OS (Android/iOS): Android 
- Mobileraker: 2.6 8-357
- Klipper: v0.12.0-32-gf0753bd3 
- Moonraker: v0.8.0-207-g6d8cb762

**Comment by Clon1998** [comment]
Fixed via #295.
Will be included in the next release
