### ISSUE TITLE
Mobileraker uses remote connection instead of local connection 

### ISSUE THREAD

**Issue by Horgul123** [Clon1998/mobileraker#306]
### Description
Mobileraker doesn't use local connection 

### Steps to Reproduce
Ioen printer in mobileraker

### Expected Behavior
User local connection of possible 

### Screenshots
See below 

### Version Information

- Device-OS (Android/iOS):  Android 14
- Mobileraker: 2.6.8-357
- Klipper:  unknown (creality K1) 
- Moonraker: 0.8.0-231
![Screenshot_2023-12-28-10-23-39-47_424ec53f7d515395b4c3ef1aaa0a00a2](https://github.com/Clon1998/mobileraker/assets/45976162/c7d7e7b1-0f98-4b6f-9dfb-d11b69cc8680)
![Screenshot_2023-12-28-10-23-18-83_424ec53f7d515395b4c3ef1aaa0a00a2](https://github.com/Clon1998/mobileraker/assets/45976162/062781c3-7135-41f4-8666-befa0b54e3c5)
![Screenshot_2023-12-28-10-24-28-54_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/Clon1998/mobileraker/assets/45976162/c537a18a-84a6-45e9-bba6-353576702b84)

**Comment by Clon1998** [comment]
Hey,
are you sure you are using the correct moonraker port?
It seems like the app is unable to connect to moonraker via the default ports.

**Comment by Horgul123** [comment]
What is the default port?
I've added port 4409 now and it seems to work. Thanks for the hint

**Comment by Clon1998** [comment]
> What is the default port? I've added port 4409 now and it seems to work. Thanks for the hint

The default port is `7125` it should be defined within the `moonraker.conf`:
```
# moonraker.conf

[server]
host: 0.0.0.0
#  The host address in which to bind the HTTP server.  Default is to bind
#  to all ipv4 interfaces.  If set to "all" the server will bind to all
#  ipv4 an ipv6 interfaces.
port: 7125
#   The port the HTTP server will listen on.  Default is 7125
ssl_port: 7130
#   The port to listen on for SSL (HTTPS) connections.  Note that the HTTPS
#   server will only be started of the certificate and key options outlined
#   below are provided.  The default is 7130.
```
