### ISSUE TITLE
Basic HTTP Auth

### ISSUE THREAD

**Issue by cpfarhood** [Clon1998/mobileraker#309]
## Feature Request
Provide a mechanism for basic http authentication

### Problem Description
I expose my printers through HAProxy with http authentication, this does not appear to be supported.

### Proposed Solution
Allow for interactive authentication or storing of passwords for printers to use with http basic authentication

### Alternatives Considered
Obico, but why not use a simple solution with no added software?

**Comment by Clon1998** [comment]
Hey, 
this is already supported. Basic Auth is simply an HTTP header in Base64 encoding.
You can read more in my answer in the related https://github.com/Clon1998/mobileraker/issues/298.
