### ISSUE TITLE
Truncated text on new printer screen

### ISSUE THREAD

**Issue by nathanielhudson** [Clon1998/mobileraker#31]
**Describe the bug**
Text on the new printer page is truncated. 
![D203B1AB-E4AC-4A18-81D3-42A786A0D93E](https://user-images.githubusercontent.com/2744848/147860561-ef59da4a-f276-43c3-b206-2bd79e35cfc6.jpeg)

**To Reproduce**
1. Go to new printer page

**Expected behavior**
Text should wrap to a new line

**Smartphone (please complete the following information):**
 - Device: iPhone8

**Mobileraker-Version
Not sure where to find this

**Comment by Clon1998** [comment]
Fixed in 6babf969cb6bb54959c6848141a8f4a6ff6a6a8b
