### ISSUE TITLE
Labeling Issue in app for time remaining.

### ISSUE THREAD

**Issue by Johnnytk36** [Clon1998/mobileraker#310]
I noticed this the other day, I think the time remaining label is incorrect in the app. It shows the title "Filament".  If you select it, you get a bunch of more times.

Also at this time the app showed a finish time of at 5:02PM and my fluid web app showed a finish time of 3:28PM. I don't know if that is because i had to exclude some objects or not. 

![IMG_1242](https://github.com/Clon1998/mobileraker_companion/assets/133730955/707aa332-4229-4997-8bc8-89497c975fbe)
![IMG_1244](https://github.com/Clon1998/mobileraker_companion/assets/133730955/59810a18-794b-4c59-8438-a0ed63cff9ed)

<img width="808" alt="Screenshot 2024-01-01 at 9 29 38 AM" src="https://github.com/Clon1998/mobileraker_companion/assets/133730955/7043fc06-f75e-47b0-9a8d-1164d5b46477">

**Comment by Clon1998** [comment]
Hey,
I moved your issue to the `mobileraker` repo.
The wrong labeling of the ETA is a known issue (See #300).

Regarding the ETA, Fluidd might use a different approach to calculate it. This was already addressed (See https://github.com/Clon1998/mobileraker/issues/138#issuecomment-1669039882), but it can still happen from time to time that the App and Web-UIs show different values. Keep in mind that both values are only approximations!
