### ISSUE TITLE
Cannot save file after first click - iOS w/iPad Pro

### ISSUE THREAD

**Issue by DrFate09** [Clon1998/mobileraker#314]
### Description
I am using an iPad Pro with Magic Keyboard to edit my configuration files within Mobileraker. If I click the Save icon, I am show the options to Save or Save and Restart. If I choose not to click either of the options and go back to editing the file, I cannot re-open those options again without closing the active file and re-opening the file (losing my changes). 

This bug does not exist when using the same device with only touch input on the Save icon.

Also, could we add some smart logic and prevent the Save icon from rendering behind the iOS keyboard button. This button shows up by default when using the Magic Keyboard.

### Expected Behavior
I should be able to Save the active file without having the fear of possibly mis-clicking on the Save icon and losing my progress :(

### Video
https://github.com/Clon1998/mobileraker/assets/22684695/9808d77e-4b34-4ef3-950b-06a68d4ae6d6

**Comment by Clon1998** [comment]
With ios2.7.0 this issue should be resolved. In addition a entirely new UI for IPad is available!
