### ISSUE TITLE
Power-on Support

### ISSUE THREAD

**Issue by cpfarhood** [Clon1998/mobileraker#316]
### Problem Description
It is common to use a relay connected to montane to power on a printer. Mainsail supports triggering this relay from the UI, Mobileraker doesn’t let you perform any actions when Klipper is shutdown.

### Proposed Solution
Implement the power on api and a button like mainsail

### Alternatives Considered
I'm currently using home assistant and the moonraker add in to perform power on remotely.

---

**Checklist**
To help us understand your feature request, please ensure you've covered the following points:
- [ ] Provided a clear description of the problem you're facing.
- [ ] Clearly outlined the proposed solution or feature.
- [ ] Mentioned any alternative solutions or ideas you've considered.
- [ ] Included any relevant context or supporting materials.

Your input is valuable in shaping the development of our project. Thank you for taking the time to submit your feature request!

**Comment by Clon1998** [comment]
> I see this was literally just added ha, thanks!

Hey,
IT was actually supported for quite a while. A change to the dashboard just broke the UI if Klipper was in shutdown state lol.
