### ISSUE TITLE
Probe-calibration window not popping up.

### ISSUE THREAD

**Issue by joelhughes004** [Clon1998/mobileraker#322]
### Description
When the probe calibration button is hit, It's a head, starts moving to the place where the probe was. The window to change values does not pop up on the current version.

### Steps to Reproduce
1. Go to The more options button
2. Click on Probe calibration.
3. See the error.

### Expected Behavior
The button is pressed. The print head moves to where the probe was. The window pops up to change the values and the save button pops up

### Screenshots
The "window" 
![Screenshot_20240120_022202_Gallery](https://github.com/Clon1998/mobileraker/assets/50282584/d901cf67-b326-4ebd-a3b4-7330f0aba230)

### Version Information

- Device-OS (Android/iOS): [OS]
- Mobileraker: [2.6.10]
- Klipper: [v0.12.0-70-g7a74888b]
- Moonraker: [v0.8.0-267-g66de18f9]

### Debug Logs
[mobileraker_2024-01-19T23-08-29.log](https://github.com/Clon1998/mobileraker/files/13997288/mobileraker_2024-01-19T23-08-29.log)
[mobileraker_2024-01-20T02-02-45.log](https://github.com/Clon1998/mobileraker/files/13997289/mobileraker_2024-01-20T02-02-45.log)
[mobileraker_2024-01-20T01-37-00.log](https://github.com/Clon1998/mobileraker/files/13997290/mobileraker_2024-01-20T01-37-00.log)
[mobileraker_2024-01-20T01-39-44.log](https://github.com/Clon1998/mobileraker/files/13997291/mobileraker_2024-01-20T01-39-44.log)
[mobileraker_2024-01-19T22-51-10.log.txt](https://github.com/Clon1998/mobileraker/files/13997292/mobileraker_2024-01-19T22-51-10.log.txt)

### Additional Context
I have a phone that is not connected to Google Play and the version is 2.6.8 and the probe calibration still works perfectly fine.
---

#### Checklist
To help us diagnose the issue, please ensure you've completed the following steps:
- [x] Provided a clear bug description.
- [x] Listed detailed steps to reproduce the issue.
- [x] Described the expected behavior.
- [x]  the Mobileraker version you are using.
- [x] Attached Mobileraker's debug log files.
- [x] Specified the version numbers of Klipper and Moonraker if applicable.

**Comment by Clon1998** [comment]
Fixed in 2.6.11
