### ISSUE TITLE
Android monochrome icons

### ISSUE THREAD

**Issue by tui2019** [Clon1998/mobileraker#328]
Monochrome icons were added in #88 but then removed in one of the updates. Is there a reason for this, or is it just a mistake?

**Comment by Clon1998** [comment]
No real reason.
I assume that the plugin I use to auto-generate the icons removed them :)

**Comment by Clon1998** [comment]
I just checked the repo and the monochrome icons are still present:

https://github.com/AustinSchulz/mobileraker/blob/dev/android/app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml

https://github.com/AustinSchulz/mobileraker/blob/master/android/app/src/main/res/drawable-mdpi/ic_launcher_monochrome.png

**Comment by tui2019** [comment]
As I understand, that is not a main repo, but rather a fork with monochrome icons.

**Comment by Clon1998** [comment]
Ohh you are right. 
I did not notice that I was not on my repo lol. I will add them again.

**Comment by tui2019** [comment]
Thank you!
