### ISSUE TITLE
Notify At Height

### ISSUE THREAD

**Issue by falo2k** [Clon1998/mobileraker#33]
We've all had those prints where it's a long print, and half way through it we're not entirely convinced that a sliced feature is going to  work - say a large transition from support to a flat surface.  I think it would be an incredibly useful feature to be able to specify, for a given print, a Z height that you want a notification for.  The new notification system can then give me a heads up that we've reached the point where I might want to go take a look and make sure things go well.

An expansion of this might be to have some way to trigger notifications in g-code, then you could add custom slicer entries to notify on features.

**Comment by Clon1998** [comment]
I will close the issue since this will be possible via the new custom `M117` user notifications supported trough mobileraker_companion.
For more info and how to test the beta visit: https://github.com/Clon1998/mobileraker_companion/blob/dev/Custom_Notifications.md
