### ISSUE TITLE
Arrange printers' list / hide some printers

### ISSUE THREAD

**Issue by wikolii** [Clon1998/mobileraker#330]
### Problem Description
The printers' list keep changing the order. I can only guess it's random.

### Proposed Solution
I think that adding filters and sorting the list would be very helpful when using a large number of machines.
The main filter I'd be interested in is "hide offline" for example.
Also sorting alphabeticaly would be nice.

### Alternatives Considered
I'm currently traveling with 3 machines and I've considered removing the ones I didn't bring with me to make the list shorter and easier to switch between them. But I'm not certain if I'll need to setup everything again when I re-add the ones left behind (macros, and other settings)

**Comment by Clon1998** [comment]
Hey,
what are you referring to when talking about the printer list? Are you talking about the overview page or about the dialog to switch between printers?

I probably don't own enough printers to experience the random ordering.

**Comment by wikolii** [comment]
I don't recall adding them on this order.
The list's order is not actually very important, but being able to filter out offline instances at least, would be cool, thanks 

![image](https://github.com/Clon1998/mobileraker/assets/14824297/6cb5ff12-6d71-4314-822d-8287b992b3b6)
![image](https://github.com/Clon1998/mobileraker/assets/14824297/f6259471-7100-4cf2-8fb6-8cfce09515de)
![image](https://github.com/Clon1998/mobileraker/assets/14824297/dbee2384-cb7b-457b-bc06-7b15e2f71219)

**Comment by wikolii** [comment]
Turns out the list respects the order the printers were added on the first place. Thanks anyways!

**Comment by Clon1998** [comment]
2.7.0 added the option to reorder printers via the "Overview Page".

**Comment by wikolii** [comment]
> 2.7.0 added the option to reorder printers via the "Overview Page".

Note: when you swipe left or right on the printer name to change from one device to another, it still follows the original order the printers were added, not the reorder.

**Comment by wikolii** [comment]
https://github.com/user-attachments/assets/a7a2c686-ff10-4234-98a1-6438e6a2287e

I was swiping right every time

**Comment by Clon1998** [comment]
Hey,
good to know. There is a possibility that the swipe action is using the wrong source and therefore is not ordered.
