### ISSUE TITLE
Z Offset settings rounded? 

### ISSUE THREAD

**Issue by igl-x2** [Clon1998/mobileraker#338]
### Description
It seems very low values for the z offset setting get rounded 

### Steps to Reproduce
Check the Screenshots of the wanted settings and the actually displayed settings 

### Expected Behavior
Dont round 
![Screenshot_2024-03-03-16-47-46-922_com mobileraker android](https://github.com/Clon1998/mobileraker/assets/129790664/87b0a87e-ff8e-4e18-8582-092955acd6bb)
![Screenshot_2024-03-03-16-47-56-823_com mobileraker android](https://github.com/Clon1998/mobileraker/assets/129790664/cebfcf4d-adda-49f1-af53-7914982d638a)

**Comment by Clon1998** [comment]
Hey,
thanks for letting me know. 
I already noticed and resolved that issue in the latest dev build.
