### ISSUE TITLE
temps not updating

### ISSUE THREAD

**Issue by Vansmak** [Clon1998/mobileraker#34]
**Describe the bug**
Set temp for hotend and bed but the displayed temp doesnt change.  I checked fluidd web and the target i set via this app did work and temps were changing. Just not showing in the app
![Screenshot_20220121-074609](https://user-images.githubusercontent.com/16037573/150557687-e5171776-59c9-4829-873f-a0591007ef8c.jpg)
![Screenshot_20220121-074619_Firefox Beta](https://user-images.githubusercontent.com/16037573/150557699-9a5c0a55-6d40-4aba-b142-cad7bb2aeb09.jpg)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Device: samsung s20

**Mobileraker-Version
This information can be found in Android's and IOS's App-Info.

**Additional context**

**Comment by Clon1998** [comment]
Hey,
this might be caused by an older version of mobileraker.
Since the main screen is not showing the bottom bar either.
Could you provide me the mobileraker's version?
