### ISSUE TITLE
Z thermal adjust not on thermals tab

### ISSUE THREAD

**Issue by SushiRemover** [Clon1998/mobileraker#340]
### Description
If you have a frame thermal sensor configured its Set as "z thermal adjust", and Shows up as a normal sensor in the thermals Tab on the Webserver. However not on the mobileraker App. 

### Screenshots
![Screenshot_2024-03-04-15-22-06-813-edit_com.mobileraker.android.jpg](https://github.com/Clon1998/mobileraker/assets/55159218/b29847b6-8e50-4ab7-b0ac-7bd71db8352d)

![Screenshot_2024-03-04-15-21-52-217_com.opera.gx.jpg](https://github.com/Clon1998/mobileraker/assets/55159218/1b2f1b1d-ac5d-4c32-a8d8-009a38d7d8d2)

### Version Information

- Device-OS (Android/iOS): Android 12
- Mobileraker: v2.6.11-401
- Klipper: v0.12.0-114
- Moonraker: v0.8.0-318

### Additional Context
For people using a frame sensor for chamber temp and also have it configured as z thermal adjust to help with rising z with the chamber temp its relatively annoying having to use the console or webserver to Check the temps when not at home.

**Comment by Clon1998** [comment]
Hey thanks for letting me know.
I will have a look at that and add the sensor/value to the dashboard
