### ISSUE TITLE
Can not fetch supporter tiers!

### ISSUE THREAD

**Issue by smolz** [Clon1998/mobileraker#341]
### Description
After paying for the lifetime subscription, the app still asks me to become a supporter.

### Steps to Reproduce
Pay money.  
Close and reopen app
Hit the hamburger menu (top left) and select "Support the Dev!"
See output:
 Can not fetch supporter tiers!

### Expected Behavior
Recognize that I have paid

### Screenshots
![Screenshot 2024-03-08 at 21 00 51](https://github.com/Clon1998/mobileraker/assets/3820601/373eab83-648a-4fdc-aef9-ca0a0b87912a)

### Version Information

- Device-OS (Android/iOS): iOS
- Mobileraker: 2.6.11 hotfix1
- Klipper: [version]
- Moonraker: [version]

### Additional Context

---

#### Checklist
To help us diagnose the issue, please ensure you've completed the following steps:
- [ ] Provided a clear bug description.
- [ ] Listed detailed steps to reproduce the issue.
- [ ] Described the expected behavior.
- [ ] Included the Mobileraker version you are using.
- [ ] Attached Mobileraker's debug log files.
- [ ] Specified the version numbers of Klipper and Moonraker if applicable.

**Comment by Clon1998** [comment]
Hey,
please reach out to me via mail (dev@mobileraker.com) or via discord (@pad_sch) as posting any transaction data that I might need is a bad idea.


Please provide me your mobileraker log via either channel

**Comment by Clon1998** [comment]
Close as this was most likely caused by apples servers.
