### ISSUE TITLE
Kitkat not compatible

### ISSUE THREAD

**Issue by pamalofeev** [Clon1998/mobileraker#35]
The mobileraker.com website says "*Works on iOS 13.6+, Android Kitkat and above".  However, on my tablet with android 4.4.2, the application cannot be installed, there is a syntax error.  Apkpure determines app compatibility only with android 7.1.

**Comment by Clon1998** [comment]
I am not the maintainer of the website. 
Mobileraker definitely never supported Android 4 (SDK 14-19). It started with support for Android 6 (Marshmellow) and currently requires Andorid 7 (SDK 25+) 
See:
https://github.com/Clon1998/mobileraker/blob/92c74903c7b77df6fa32d021a8cc808c635d3e80/android/build.gradle#L3-L6

**Comment by jniebuhr** [comment]
it's changed on the site

**Comment by Misterke** [comment]
It's a pity that support only starts with Nougat as there are still so many Samsung tablets out there running Marshmallow.

**Comment by Clon1998** [comment]
Yes for sure.
But I don't have the needs nor do I have the time to make it compatible with an 9 year old android version.
The code is on GitHub, so feel free to adapt it for 4.4.
