### ISSUE TITLE
Time remaining in notifications is wrong

### ISSUE THREAD

**Issue by spitfire** [Clon1998/mobileraker#350]
![image](https://github.com/Clon1998/mobileraker/assets/42872/01fe925e-0f7e-4c89-9680-69a39e68b2a0)
The time in notifications is wrong. Live activities and mainsail show the correct one, printer's timezone is set up correctly.

**Comment by Clon1998** [comment]
> ![image](https://private-user-images.githubusercontent.com/42872/317883521-01fe925e-0f7e-4c89-9680-69a39e68b2a0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE2NjEyNjcsIm5iZiI6MTcxMTY2MDk2NywicGF0aCI6Ii80Mjg3Mi8zMTc4ODM1MjEtMDFmZTkyNWUtMGY3ZS00Yzg5LTk2ODAtNjlhMzllNjhiMmEwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI4VDIxMjI0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThjZGY5NTQ5YzUwOTI2YThkNjUxYWU1NzlhMTYwNjg4ZmNkNGQ3YTc2NzVlOGYxMmVhM2JkZTUyYmJjMzEzNjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.de01OgnVMvhaoYT3HstNbkk3AzLcqAbLpPBKOdVfo90) The time in notifications is wrong. Live activities and mainsail show the correct one, printer's timezone is set up correctly.

Is the timezone also correct in the mobileraker.conf file?

**Comment by spitfire** [comment]
It is not, but to make it stranger it is set to CST, which is 6 hours behind, and the notification's time is only 1 hour behind. I'll try to adjust it once the print is over, cause changing it would probably restart something and interrupt it;)

**Comment by spitfire** [comment]
Adjusted it to CET, restarted Mobileraker companion (through mainsail) and it's still showing the same offset/timezone on the next print.

**Comment by spitfire** [comment]
![image](https://github.com/Clon1998/mobileraker/assets/42872/dfe6dee3-e453-4d2b-8845-bfaa3e7fdf10)
Now it is correct ¯\_(ツ)_/¯
