### ISSUE TITLE
Webcam panel shown despite no webcam configured

### ISSUE THREAD

**Issue by AndreKR** [Clon1998/mobileraker#354]
### Description
I don't have a webcam and there is no webcam configured in the printer settings.

Yet, since I updated Mobileraker (I know, my own fault) there is a webcam panel on the main screen saying "Invalid arguments".

### Steps to Reproduce
1. Make sure there is no webcam configured for a printer.
2. Open Mobileraker.
3. See the error.

### Expected Behavior
I expect there to be no webcam panel when there is no webcam available.

### Screenshots
![image](https://github.com/Clon1998/mobileraker/assets/1188538/7b8a6892-ca1d-4cdc-955d-5e67a0b74bb6)

![image](https://github.com/Clon1998/mobileraker/assets/1188538/934f80b4-5f29-4b6d-aad7-574963933ebc)

### Version Information

- Device-OS (Android/iOS): Android
- Mobileraker: 2.6.14-424
- Klipper: v0.12.0-118-g18de421c
- Moonraker: v0.8.0-320-g6b1b8c5

### Debug Logs
[mobileraker_2024-04-08T02-12-37.log](https://github.com/Clon1998/mobileraker/files/14899564/mobileraker_2024-04-08T02-12-37.log)

**Comment by Clon1998** [comment]
Thanks for reporting this bug.
I will double-check that, but I thought I had already fixed it. Maybe the fix is currently only on dev tho.

**Comment by Clon1998** [comment]
Fixed in 2.6.15/2.6.16
