### ISSUE TITLE
Alarm on layer number reached 

### ISSUE THREAD

**Issue by Mrqozy** [Clon1998/mobileraker#356]
Hello, first love your app, I donated already. 

Secondly would it be possible to add an alarm or notification on a specific layer? 

Some layers are critical such as bridging layers and would love to receive a notification when the layer is for example 2 layers away. 

Thank you.

**Comment by Clon1998** [comment]
Hey,
This is not natively supported as of now. However, you can add it manually via the slicer and [custom notifications](https://github.com/Clon1998/mobileraker_companion/blob/main/docs/Custom_Notifications.md).

**Comment by Mrqozy** [comment]
I see thank you.

**Comment by Clon1998** [comment]
Duplicate of #235
