### ISSUE TITLE
Spoolman Rounding

### ISSUE THREAD

**Issue by brando132** [Clon1998/mobileraker#364]
## Feature Request

Spoolman spool info card uses poor formatting above 1kg. instead of a gram unit display (451/1000grams), it uses kilograms when loaded with spools above 1kg. (3kg / 5kg)

### Proposed Solution
Change the default formatting to display in grams, or increase the number of sigfigs. 
3kg / 5kg  --> 3.141kg / 5kg or 3141g / 5000g

### Alternatives Considered
Potentially enable this as a toggle in app settings.

**Comment by spitfire** [comment]
![image](https://github.com/Clon1998/mobileraker/assets/42872/99f4ae26-fa90-4126-b5bb-3a19625d4d6d)
It is showing like this on a 1100g spool (Jayo makes 1,1kg ones) where I've used ~50g.

**Comment by Clon1998** [comment]
Hey,
I will update the implementation to actual show a decimal point for kg too or as suggested make it configurable.

**Comment by Clon1998** [comment]
Fixed 
<img width="367" alt="image" src="https://github.com/Clon1998/mobileraker/assets/10357775/24a3ce53-6eff-4b95-a06b-6053de954b21">

**Comment by spitfire** [comment]
Yessss. Accuracy to the second decimal (no more, and no less) is exactly what we needed :)

**Comment by Clon1998** [comment]
Added in 2.7.0.
Just triggered the build. Rollout should start tomorrow und ramp up slowly over the next 7 days.
