### ISSUE TITLE
2.6.17-460 - main screen broken?

### ISSUE THREAD

**Issue by pwlgrzs** [Clon1998/mobileraker#365]
### Description
A clear and concise description of the bug.

### Steps to Reproduce
1. Go to 'Main screen'
2. See the error.

### Expected Behavior
I got an app update today to version 2.6.17-460 and main application screen appears broken, I'd expect address/status/progress.

### Screenshots
Top is inactive printer, Voron only shows the camera preview and nothing else.
![Screenshot_20240430_004914](https://github.com/Clon1998/mobileraker/assets/7893951/453bf523-673a-4501-9f3b-348e3ad4856a)

### Version Information

- Device-OS (Android/iOS): Android
- Mobileraker: 2.6.17-460
- Klipper: v0.12.0-117-g71604b71
- Moonraker: v0.8.0-343-g0f2e3d7c

### Debug Logs
[mobileraker_2024-04-30T00-49-10.log](https://github.com/Clon1998/mobileraker/files/15155904/mobileraker_2024-04-30T00-49-10.log)

### Additional Context
Add any other relevant context about the problem here.

---

#### Checklist
To help us diagnose the issue, please ensure you've completed the following steps:
- [X] Provided a clear bug description.
- [X] Listed detailed steps to reproduce the issue.
- [X] Described the expected behavior.
- [X] Included the Mobileraker version you are using.
- [X] Attached Mobileraker's debug log files.
- [X] Specified the version numbers of Klipper and Moonraker if applicable.

**Comment by Clon1998** [comment]
Thanks...
Working on it
