### ISSUE TITLE
V2.7.0 on iOS 17.5.1 Broken

### ISSUE THREAD

**Issue by TheMasterOfTech** [Clon1998/mobileraker#378]
Information doesn’t load for the printer. Octoeverywhere connects, but the UI seems to have broken how to interpret the information as all I get is a grey screen after the connection is established. I will see if local will make any difference when I get home but I think it’s something in this latest release that broke it.
![IMG_7072](https://github.com/Clon1998/mobileraker/assets/117061904/6d134610-42f1-4b53-bf07-ffac4a7302b2)

I am running iOS 17.5.1 on an iPhone 12 Pro with Mobileraker version 2.7.0.

**Comment by Clon1998** [comment]
Hey,
can you provide me the app's logs?
They are located at the very bottom of the app settings.

**Comment by TheMasterOfTech** [comment]
@Clon1998 , I don’t see a way to export out the log other than viewing it. Do I need to take snapshots and upload here?

**Comment by Clon1998** [comment]
I've already located the issue. It was caused by an error in the remote announcements. It might take a few hours for the new changes to be published on your device. If the error persists after 24 hours, please let me know!

To share the logs, you should be able to press "Share" in the log dialog.

**Comment by TheMasterOfTech** [comment]
> I've already located the issue. It was caused by an error in the remote announcements. It might take a few hours for the new value to be published on your device. If the error persists after 24 hours, please let me know!
> 
> To share the logs, you should be able to press "Share" in the log dialog.

@Clon1998 , I don’t see a Share button within the prompt, unless I’m not understanding?

**Comment by Clon1998** [comment]
> > I've already located the issue. It was caused by an error in the remote announcements. It might take a few hours for the new value to be published on your device. If the error persists after 24 hours, please let me know!
> 
> > 
> 
> > To share the logs, you should be able to press "Share" in the log dialog.
> 
> 
> 
> @Clon1998 , I don’t see a Share button within the prompt, unless I’m not understanding?

https://github.com/Clon1998/mobileraker/assets/10357775/c21943db-c74d-4880-8536-b6d5475c8344

**Comment by TheMasterOfTech** [comment]
> > > I've already located the issue. It was caused by an error in the remote announcements. It might take a few hours for the new value to be published on your device. If the error persists after 24 hours, please let me know!
> > 
> > 
> > > 
> > 
> > 
> > > To share the logs, you should be able to press "Share" in the log dialog.
> > 
> > 
> > @Clon1998 , I don’t see a Share button within the prompt, unless I’m not understanding?
> 
>  trim.3E456842-15A1-430E-9246-9155EE2C3B2C.MOV

Didn’t think it was the save button but makes sense lol. Sorry about that! Here you go in case you find something else:
[mobileraker_2024-06-26T10-21-45 2.log](https://github.com/user-attachments/files/15993705/mobileraker_2024-06-26T10-21-45.2.log)
[mobileraker_2024-06-26T11-01-34 2.log](https://github.com/user-attachments/files/15993706/mobileraker_2024-06-26T11-01-34.2.log)
[mobileraker_2024-06-26T10-22-09 2.log](https://github.com/user-attachments/files/15993708/mobileraker_2024-06-26T10-22-09.2.log)
[mobileraker_2024-06-26T10-34-24 2.log](https://github.com/user-attachments/files/15993709/mobileraker_2024-06-26T10-34-24.2.log)
[mobileraker_2024-06-26T10-19-18 2.log](https://github.com/user-attachments/files/15993710/mobileraker_2024-06-26T10-19-18.2.log)
[text 2.txt](https://github.com/user-attachments/files/15993712/text.2.txt)

**Comment by spitfire** [comment]
Same on 18b2. On he bright side the live activity started working again;)

**Comment by TheMasterOfTech** [comment]
Issue seems resolved, but be it known that I did have to uninstall and reinstall in order to get “the fix” as it might be something cached and was using old configuration.
![IMG_7091](https://github.com/Clon1998/mobileraker/assets/117061904/eb358c62-73f6-4b01-98b7-1d6710273ec0)

**Comment by Clon1998** [comment]
> Issue seems resolved, but be it known that I did have to uninstall and reinstall in order to get “the fix” as it might be something cached and was using old configuration.
> 
> ![IMG_7091](https://github.com/Clon1998/mobileraker/assets/117061904/eb358c62-73f6-4b01-98b7-1d6710273ec0)
> 
> 

It was related to my remote in app announcements.
They updated at most every 12hrs. So it just took some time. I also just updated the implementation to work in real time to ensure such an issue can be fixed faster next time.
