### ISSUE TITLE
ETA is wrong on app and widget.

### ISSUE THREAD

**Issue by BlackNet** [Clon1998/mobileraker#384]
The printer shows the previous prints are 7 hours and 1 minute.  I started this current job at 3pm (EST), one hour has elapsed.  The ETA panel on the web interface shows 10:43 PM (close to accurate), while the time on the app shows 2:22 AM.

This print was setup with ocaslicer.  Is there something i can do to get that to read the correct ETA? The mobileraker conf shows EST. Wondering if this is an orca slicer thing.

**Comment by BlackNet** [comment]
it is in the app AND on the widget on the lock screen as well.

**Comment by Clon1998** [comment]
Alright,
there is not much else you can do.
I need to look into this, but mobileraker uses the same formula as mainsail (Unless they changed it again).
Can you compare all ETA values (Long press the ETA and the app shows you each category).

**Comment by BlackNet** [comment]
Hmm. Looks like the slicer and file is correct. The file is what is wrong and it seems to be using that. 

![image](https://github.com/Clon1998/mobileraker/assets/2658/50735888-1d39-4cb7-88d7-e9cd6b25e67c)

**Comment by Clon1998** [comment]
That looks fine,
Can you tell me what source you enabled for the ETA calculation in your Webinterface? Also are you using Mainsail or Fluidd?
To see the selected sources in Fluidd: Settings -> General -> Print ETA calculation
To see the selected sources in Mainsail: Settings -> General -> Print ETA calculation

**Comment by BlackNet** [comment]
I have both mainsail and fluidd on this machine.  I have fluidd set to relative file position, mainsail to file, filament, slicer.

**Comment by Clon1998** [comment]
In that case mainsail should also be off as mobileraker currently uses all available sources.

**Comment by BlackNet** [comment]
![Screenshot 2024-07-10 172117](https://github.com/Clon1998/mobileraker/assets/2658/ffa6cd76-28c4-4fd4-b222-70c7bb8f8dbb)
![Screenshot 2024-07-10 172109](https://github.com/Clon1998/mobileraker/assets/2658/2ff962ef-e38b-4751-b44e-bddcfb4e40f6)

This is what each shows.

**Comment by BlackNet** [comment]
I guess this swing would be different in several cases. Making it configurable would be the best. That way, each user could change it according to what they are printing.

**Comment by Clon1998** [comment]
2.7.1 added that option
