### ISSUE TITLE
App freezes on camera fullscreen

### ISSUE THREAD

**Issue by Bleach3D** [Clon1998/mobileraker#387]
### Description
When you want to open the fullscreen webcam image in the printer overview, the app freezes, screen turns gray.

### Steps to Reproduce
1. Go to printer overview page
2. klick on fullscreen button.
3. App crashes.

### Expected Behavior
Fullscreen should be shown.

### Screenshots
![image](https://github.com/user-attachments/assets/e005ddfb-b67f-4644-a817-bbb4b800fec6)
![image](https://github.com/user-attachments/assets/00d9fa0b-501d-4a9a-97d5-859f88ca1421)

### Version Information

- Device-OS (iOS): 17.5.1
- Mobileraker: 2.7.0
- Klipper: 
- Moonraker: 

### Debug Logs
Please attach the log files generated by Mobileraker. You can find them by navigating to the app's settings page, scrolling to the bottom, and pressing the `Debug Logs` button.
-> sorry, cant find it.

### Additional Context
Add any other relevant context about the problem here.

---

#### Checklist
To help us diagnose the issue, please ensure you've completed the following steps:
- [x] Provided a clear bug description.
- [x] Listed detailed steps to reproduce the issue.
- [x] Described the expected behavior.
- [x] Included the Mobileraker version you are using.
- [ ] Attached Mobileraker's debug log files.
- [ ] Specified the version numbers of Klipper and Moonraker if applicable.

**Comment by Clon1998** [comment]
Hey,
Thanks for reporting this issue.
Since yesterday V2.7.1 is rolling out since which addresses the issue alongside some other bug fixes and improvements.
