### ISSUE TITLE
iOS Notification image flipped

### ISSUE THREAD

**Issue by Bleach3D** [Clon1998/mobileraker#388]
### Description
The camera image shown in the notification on IOS devices seem to be flipped

### Steps to Reproduce
1. start a print
2. look at the notification
3. see flipped image
(Camera image is flipped in the the camera settings, since it is mounted overhead)

### Expected Behavior
The image should have the same orientation as in the opened app.

### Screenshots
![image](https://github.com/user-attachments/assets/38f2d516-006e-4183-90c7-8cc207e26cb0)
### Version Information

- Device-OS (iOS): 17.5.1
- Mobileraker: 2.7.0
- Klipper: 
- Moonraker:

### Additional Context

---

#### Checklist
To help us diagnose the issue, please ensure you've completed the following steps:
- [x] Provided a clear bug description.
- [x] Listed detailed steps to reproduce the issue.
- [x] Described the expected behavior.
- [x] Included the Mobileraker version you are using.
- [ ] Attached Mobileraker's debug log files.
- [ ] Specified the version numbers of Klipper and Moonraker if applicable.

**Comment by Clon1998** [comment]
The companion is doing exactly what you configured. The rotation is not yet synced/taken from moonraker. Therfore, you will ned to configure the rotation in the `mobileraker.conf` file via the `snapshot_rotation: <>` entry.
https://github.com/Clon1998/mobileraker_companion?tab=readme-ov-file#companion---config
