### ISSUE TITLE
Latest app bugs

### ISSUE THREAD

**Issue by RichardLiba** [Clon1998/mobileraker#389]
### Description
I have found two bugs on Overview screen

### Steps to Reproduce
1. Go to Overview
2. Click on Full screen for any of the camera streams
3. observe gray screen 

### Expected Behavior
I can see the full screen of my stream.

### Version Information

- Device-OS (Android/iOS): Android
- Mobileraker: 2.7.0- 501

**Comment by Clon1998** [comment]
Hey,
the issue with the can was resolved in 2.7.1 which started rolling out slowly.

Gwkebz, you mention that you have found two bugs but only mention one?

**Comment by RichardLibaBL** [comment]
Yes, sorry as I started writing all the checklists I thought I will not write the other one here..
Progress percentage on overview is flickering. .like it's visibility is changing or something like that.

**Comment by Clon1998** [comment]
> Yes, sorry as I started writing all the checklists I thought I will not write the other one here..
> 
> Progress percentage on overview is flickering. .like it's visibility is changing or something like that.

Noticed that as well.
It's already fixed in dev/2.7.1 partially

**Comment by Clon1998** [comment]
2.7.1 should have fixed that.
Feel free to reopen if the issue persists.
Note that the state might still lag/shimmer in 2.7.1. I already fixed it in my dev branch tho.
