### ISSUE TITLE
Tablet overview view is not right

### ISSUE THREAD

**Issue by drumstick77** [Clon1998/mobileraker#392]
### Description
A clear and concise description of the bug.

### Steps to Reproduce
4. See the error.

### Screenshots
If applicable, add screenshots to help explain the problem.

### Version Information

- Device-OS (Android/iOS): android 14
- Mobileraker: latest
- Klipper: latest
- Moonraker: latest

### Debug Logs
Please attach the log files generated by Mobileraker. You can find them by navigating to the app's settings page, scrolling to the bottom, and pressing the `Debug Logs` button.

### Additional Context
Add any other relevant context about the problem here.

---

#### Checklist
To help us diagnose the issue, please ensure you've completed the following steps:
- [ ] Provided a clear bug description.
- [ ] Listed detailed steps to reproduce the issue.
- [ ] Described the expected behavior.
- [ ] Included the Mobileraker version you are using.
- [ ] Attached Mobileraker's debug log files.
- [ ] Specified the version numbers of Klipper and Moonraker if applicable.

**Comment by Clon1998** [comment]
Please provide a more detailed description and ensure you complete all tasks of the check list.
