### ISSUE TITLE
Dismiss 'Tablet Layout Status' notification on tablet

### ISSUE THREAD

**Issue by amercer86** [Clon1998/mobileraker#395]
## Feature Request
The ability to dismiss the 'Tablet Layout Status' notification warning users that tablet layout is currently under development. 

### Problem Description
I haven't experienced any issues with the Tablet Layout other than I'm unable to dismiss the 'Tablet Layout Status' notification which appears to be a permanent fixture to the top of the dashboard.

### Proposed Solution
Add the ability to dismiss or disable this notification.

**Comment by Clon1998** [comment]
Hey,
I already removed the banner in the dev branch :)
