### ISSUE TITLE
Limit video to 1 frame per X seconds

### ISSUE THREAD

**Issue by ChaosBlades** [Clon1998/mobileraker#396]
I have a large printer running 3264x2448 (full sensor resolution) at 15 fps and mobileraker can't even display it due to it using 125Mb/s 😅. I have to go down to 1600x1200 in order to get it to actually display. Going to that resolution makes it hard to see anything on such a large printer. I can however limit the FPS to 1 in crowsnest but this also limits Fluidd to 1 FPS. Would be nice if you could limit the FPS within mobileraker to 1 FPS or even better yet 1 frame per 5 seconds. These printers are not using H.264 streams. These are usually as seen above gigantic motion jpeg streams. This would allow the app to run faster and use substantially less bandwidth.

Would like to see an option similar to Fluidd with an Adaptive stream that you can set a target FPS outside of crowsnest but since this is for mobile and can be viewed over a cellular network with high overage costs it would be even better to add a limit for 1 frame per X seconds.

**Comment by Clon1998** [comment]
Hey,
this should already be supported. 
Open the printer settings (Open Menu -> Gear Icon at the top -> Scroll to WebCams -> Press ADD -> Select Mjpeg Adaptive -> Limit FPS -> Save -> Select the newly created cam).
