### ISSUE TITLE
Cancel Confirmation

### ISSUE THREAD

**Issue by leitenky** [Clon1998/mobileraker#399]
### Problem Description
When selecting "...." Menu you can accidentally select cancel instead of pause and ruin a print. 

### Proposed Solution
 Add a confirmation pop-up after selecting cancel. (Just like the e-stop confirmation)

**Comment by Clon1998** [comment]
Hey,
I'll make sure to add this.

**Comment by jmedlin** [comment]
I’d also like this feature, I just tried to hit pause on a print this morning to change the spool and fat fingered the button.  I accidentally ruined a 19 hour print.

**Comment by Clon1998** [comment]
@jmedlin what Version are you using. I've added this request already:

https://github.com/user-attachments/assets/3792cea7-8b2c-4908-8f9c-83cc98932818

**Comment by Clon1998** [comment]
> I’d also like this feature, I just tried to hit pause on a print this morning to change the spool and fat fingered the button.  I accidentally ruined a 19 hour print.

Actually, I'll verify if it also shows the dialog while a print is paused.
