### ISSUE TITLE
Streamlining manually entered values

### ISSUE THREAD

**Issue by iamrans0m00** [Clon1998/mobileraker#406]
### Problem Description
When setting fields like fan speed/pins to enter a value you have to tap on the field and then delete the existing value and then can enter the correct value and then need to tap confirm

### Proposed Solution
When the dialog comes up to enter the value
-highlight the existing value
-automatically bring up the numpad 
-also give the option to confirm the value by tapping on the done button on the numpad

### Alternatives Considered
Not submitting this request and deal with the extra taps.

### Additional Context
None

---

**Checklist**
To help us understand your feature request, please ensure you've covered the following points:
- [x] Provided a clear description of the problem you're facing.
- [x] Clearly outlined the proposed solution or feature.
- [x] Mentioned any alternative solutions or ideas you've considered.
- [x] Included any relevant context or supporting materials.

Your input is valuable in shaping the development of our project. Thank you for taking the time to submit your feature request!

**Comment by Clon1998** [comment]
Greate Idea!
I actually implemented something similar in other parts of the app.

Just committed the changes :)
