### ISSUE TITLE
Eta date for long prints

### ISSUE THREAD

**Issue by Bad-Hackerman** [Clon1998/mobileraker#434]
### Problem Description
When printing long prints the Eta always shows the time when done but not the date, which can become a bit confusing for prints that cross 3 calendar days. 

### Proposed Solution
Give the date of when the print is done as well as the time

### Alternatives Considered
Add a +1 for each additional day from print start 

Awesome project!!

**Comment by Clon1998** [comment]
Hey,
thanks for letting me know. Frankly I never noticed that since my prints rarely exceed 1 day.

Just to confirm you are talking about the eta shown in the app on the dashboard?

Not about eta on:
- Notifications 
- GCode page

**Comment by Bad-Hackerman** [comment]
Yes the one in the app, not the one in the notification page
![Screenshot_20241127-022359](https://github.com/user-attachments/assets/357cddbf-8227-465f-bc32-ba1b51af043f)

![Screenshot_20241127-022809](https://github.com/user-attachments/assets/6eb0dc7d-3bf9-43ba-aa51-e3f3ea8d30b8)

Forgot to add the screenshot on the original post...

**Comment by Clon1998** [comment]
Let me know if this is clear indicator for next `n` days
<img width="344" alt="image" src="https://github.com/user-attachments/assets/f70bb8ab-36e8-4c0b-9124-18fa293508ef">
