### ISSUE TITLE
Contribution

### ISSUE THREAD

**Issue by AntoszHUN** [Clon1998/mobileraker#44]
Hi!

Would you like to know if this program is under development? If so, I would be happy to support you in creating the Hungarian language. Is there a need for it?

**Comment by Clon1998** [comment]
Hey 👋,
yes the app is on constant development.
However, feel free to add any translation you want. Checkout the dev branch to get the latest language file 😉
Currently only English is fully implemented. There is a file for the german language however i don't have the time to properly add all language keys in German.

**Comment by Clon1998** [comment]
Here you can find the english language file.
https://github.com/Clon1998/mobileraker/blob/dev/assets/translations/en.json

**Comment by AntoszHUN** [comment]
> 



> Hey 👋, yes the app is on constant development. However, feel free to add any translation you want. Checkout the dev branch to get the latest language file 😉 Currently only English is fully implemented. There is a file for the german language however i don't have the time to properly add all language keys in German.

Thanks for the quick response! Then I do the Hungarian language quickly.
