### ISSUE TITLE
K2 plus error

### ISSUE THREAD

**Issue by Florian6901** [Clon1998/mobileraker#445]
constant error after adding k2 plus on the app.
![IMG_4029](https://github.com/user-attachments/assets/9097fc56-eaea-402e-ad98-34aaedf33796)

ios

**Comment by Clon1998** [comment]
Can you provide me the installed app version, located at the very bottom of the settings page or at the top of the changelog page.

This issue should be resolved in 2.8.3

**Comment by Florian6901** [comment]
I reinstalled the app and I no longer have any errors. I am on 2.8.3. Thank you

Le 14 déc. 2024 à 01:37, Patrick Schmidt ***@***.***> a écrit :

﻿

Can you provide me the installed app version, located at the very bottom of the settings page or at the top of the changelog page.

This issue should be resolved in 2.8.3
