### ISSUE TITLE
Move console to a swipe space to the right of macros

### ISSUE THREAD

**Issue by jacrify** [Clon1998/mobileraker#49]
**Is your feature request related to a problem? Please describe.**

I use macros a lot in this app. but a lot of them spit out console out (eg “printer not homed”). I need to tap left nav, console, to view. Sounds precious I know but it’s friction, and taps take a bit of fine motor control whereas a swipe can be sloppy.

**Describe the solution you'd like**

pull the console screen from where it is now to a screen “to the right of” macros. Then you could run a macro and swipe right to see output. 
**Describe alternatives you've considered**
Putting a console pane on the macro screen
**Additional context**
If you were going to do this then you might as well put files as another swipe space :)

dude I love this app

**Comment by Clon1998** [comment]
Related to #11
