### ISSUE TITLE
Cancelled print shows as paused

### ISSUE THREAD

**Issue by jacrify** [Clon1998/mobileraker#50]
**Describe the bug**
After cancelling print, app thinks it is paused. I cannot start another print in app

**To Reproduce**

Start a print. 
Cancel it
Look at status ( shows as paused)
Check print in fluid ui, print shows as cancelled. 
Start another print, app picks it up

**Expected behavior**
App picks up that print is cancelled

**Screenshots**
![image](https://user-images.githubusercontent.com/9527059/170802599-b1ee253f-4104-4ebc-b32e-e36590820a4f.jpeg)
![image](https://user-images.githubusercontent.com/9527059/170802617-0bbb1a20-9361-409d-a90d-54a83bf8d799.jpeg)

**Desktop (please complete the following information):**
iOS, iPad and iPhone

**Smartphone (please complete the following information):**

**Mobileraker-Version
This information can be found in Android's and IOS's App-Info.
1.61.1-15

**Additional context**

**Comment by Clon1998** [comment]
Works fine on all 3 devices for me.
Can you give me an update if the issue still is valid on your side?

**Comment by jacrify** [comment]
It’s working fine Patrick. Sorry it’s a user error
