### ISSUE TITLE
(Trivial bug) Enter key on keyboard does not submit console command on ios

### ISSUE THREAD

**Issue by jacrify** [Clon1998/mobileraker#54]
**Describe the bug**

When hitting done on soft keyboard or enter on physical (bluetooth keyboard) at the end of typing a console command, nothing happens. You need to click the submit arrow (oh the pain, the pain!)

**To Reproduce**

**Expected behavior**

Physical keyboard enter key should submit the command
**Screenshots**

**Desktop (please complete the following information):**
iOS
**Smartphone (please complete the following information):**

**Mobileraker-Version
This information can be found in Android's and IOS's App-Info.
1.6.1-15
**Additional context**

I suspect adding 

`onEditingComplete: model.onCommandSubmit`

to the TextField on line 121 in console_view.dart will fix this, but I'm just guessing.

**Comment by Clon1998** [comment]
I guess youre using an IPad with a keyboard.
I am unable to test my implementation against it.
However testing on android emulator seems to suggest that passing enter will now submit the entered command !

**Comment by jacrify** [comment]
Yeah I originally raised this as I couldn't hit enter on my ipad
(bluetooth) keyboard. But it also happens with the onscreen keyboard.

Thanks for fixing
