### ISSUE TITLE
Doesn't show second extruder status

### ISSUE THREAD

**Issue by DeanCording** [Clon1998/mobileraker#59]
**Describe the bug**
Mobilerake only shows the status of the first extruder on a multi-extruder printer

When printing from the second extruder, it only display the first extruder temp.

**Expected behavior**
Should should the status of the currently active extruder.

**Smartphone (please complete the following information):**
 - Android 12

**Mobileraker-Version
1.6.2

**Additional context**

**Comment by Clon1998** [comment]
Hey,
are you by any chance open to test my implementation (Commit: 5b8fbd3d51ca4bcadc189647aa0e40c65b0f7604).
Github actions should build a new APK : https://github.com/Clon1998/mobileraker/releases/tag/android1.7.0-b24


Please let me know if it works since I don't have a dual extruder printer!

**Comment by DeanCording** [comment]
Seems to work ok in landscape mode
![Screenshot_2022_0704_204311](https://user-images.githubusercontent.com/251170/177139378-a8715a90-bf08-4763-9285-eeb588490232.png)

But in portrait mode there is too much space between the cards

![Screenshot_2022_0704_204404](https://user-images.githubusercontent.com/251170/177139443-7d0f43bd-3b52-41ad-904a-1b915e46a36a.jpg)

**Comment by Clon1998** [comment]
I've decreased the min size for the cards in 4e3a8935eff1ba183508045a292bf3288ea2da2f.
Here you can see a 4.7inch emulator screenshot. I hope that fixes your issue. Feel free to open a new issue if it still is not fixed once I release a new beta build!
![image](https://user-images.githubusercontent.com/10357775/177295239-de32fec0-e54e-4b0e-95cd-430396e6cfbc.png)
