### ISSUE TITLE
Camera does not flip when selected in settings

### ISSUE THREAD

**Issue by jacrify** [Clon1998/mobileraker#60]
**Describe the bug**

**To Reproduce**
Go to camera in settings
Choose flip vertical or horizontal
Hit save
Camera does not flip
Same result on both cam modes
**Expected behavior**
Image should flip. It does flip in front end (mainsail) when I do the same thing there
**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
iOS 15.6 iPhone XR
**Mobileraker-Version
This information can be found in Android's and IOS's App-Info.
1.6.2-16

**Additional context**

**Comment by Clon1998** [comment]
Ion my iphone it works fine.
However, if you flip the cam in the printer's settings and press save, does it close the edit screen or does it stay in the edit screen?

**Comment by jacrify** [comment]
Oh dude I’m so sorry: it’s working on mine too, but the camera is rotated
90 degrees so vertical flips horizontal and horizontal flips vertical! I
was looking for the wrong result.

**Comment by jacrify** [comment]
User error : user cannot tell the difference between horizontal and vertical
