### ISSUE TITLE
White/Grey space in dashboard

### ISSUE THREAD

**Issue by Aasikki** [Clon1998/mobileraker#61]
**Describe the bug**
White/Grey space in dashboard in the fist tab (overview?) under the card with percentage and eta etc.

**To Reproduce**
1. Go to dashboard > first tab
2. There white space in place of everything that should be under the fist card.

**Expected behavior**
See printer controls.

**Screenshots**
![Screenshot_20220703-150823_Mobileraker](https://user-images.githubusercontent.com/58399890/177038960-a20773a3-2efc-4fd4-9e5f-a83ac1f08ef6.png)

**Smartphone (please complete the following information):**
 - Device: OnePlus 7 Pro

 - OS: Android 12, Pixel experience 
SQ3A.220605.009.A1
PixelExperience_Plus_guacamole-12.1-20220615-2253-OFFICIAL

**Mobileraker-Version**
 1.7.0-23

**Additional context**
Please note I'm currently running a custom rom on my phone, this shouldn't affect mobile raker though. 

I tried resetting app by force stopping and clearing storage + cache and tried if not having webcam configured would help, couldn't find a fix/workaround. Also tried reinstalling.

**Comment by Clon1998** [comment]
Was related to the temperature graphs. Should be fixed in 0d9e4d070e408197519c418b00c36e41c9d56a66
