### ISSUE TITLE
Status page broken

### ISSUE THREAD

**Issue by Leithian** [Clon1998/mobileraker#62]
**Describe the bug**
When opening the status page there is only a grey screen shown except for the one-word printer status like "Standby". All other pages are displayed correctly.

**To Reproduce**
1. Go to the main screen / Open the app

**Screenshots**
![Screenshot_20220704-135349](https://user-images.githubusercontent.com/6052614/177149740-373f0f48-af73-474f-b81c-45b192c9a843.png)

**Smartphone (please complete the following information):**
 - Device: Pixel 4XL
 - OS: Android 12

**Mobileraker-Version
1.7.0-23

**Additional context**
Also clearing cache, app data or reinstalling doesn't work

**Comment by Clon1998** [comment]
Related to #61.
Just triggered a new build for the beta test that should resolve the issue.

**Comment by Leithian** [comment]
Thanks, sorry that I didn't see the other report, my bad!
