### ISSUE TITLE
Customize what events generate alerts

### ISSUE THREAD

**Issue by CornHead764** [Clon1998/mobileraker#71]
**Is your feature request related to a problem? Please describe.**
When using Mobileraker with the companion for notifications, it sends notifications for events such as print pauses. When coupled with something like the [moonraker timelapse plugin](https://github.com/mainsail-crew/moonraker-timelapse), you get a push notification every time it takes a screenshot, which is typically at every layer change.

**Describe the solution you'd like**
I would like to see a way to customize what generates an alert. In my case, I would likely disable print pauses.

**Describe alternatives you've considered**
I've thought about removing the companion for no notifications, but I would like progress and complete notifications still. Maybe the companion could detect the timelapse screenshot gcode and pause alerts temporarily.

**Additional context**
https://github.com/mainsail-crew/moonraker-timelapse

**Comment by Clon1998** [comment]
Was added in ebb9fbfa231a65dc3e9a43783c865c8f998dda29 .
So far it seems to be working as it is included in the latest beta builds. I will close the issue for now. If there is any problem with the implementation just reopen the issue.
