### ISSUE TITLE
Chamber temperature not showing in the app

### ISSUE THREAD

**Issue by pavel75190** [Clon1998/mobileraker#74]
Only the standard temperatures are shown in the dashboard. I set up the chamber temperatures in the config and it works in the browser but is not showing up in the app

![10A475D3-65D2-42BA-BC3A-A77A5737BFFD](https://user-images.githubusercontent.com/114373726/192182818-8d768685-afa8-471f-8464-29acb7ed7b4f.png)
![B6F47138-480A-4470-8416-F0F601547429](https://user-images.githubusercontent.com/114373726/192182819-84ca2b9e-34ad-4931-97e2-7be214a5096c.png)

**Comment by Clon1998** [comment]
Hey,
can you share the config section of the chamber heater/sensor so I can reproduce it on my setup?
