### ISSUE TITLE
Specify input parameters for klipper macros

### ISSUE THREAD

**Issue by dummylabs** [Clon1998/mobileraker#77]
**Is your feature request related to a problem? Please describe.**
I've got a bunch of parametrised klipper macros which I'd like to run from within the app. It doesn't make much sense to run them with default values.

**Describe the solution you'd like**
It would be great if mobileraker is able to run macro with parameters specified by user, like fluidd does. E.g. when user long press a macro badge, the dialog appears.

**Additional context**
Attached is an example of parameters dialog for pressure advance calibration macro from fluidd.

<img width="159" alt="image" src="https://user-images.githubusercontent.com/4209521/195099399-7dc162f2-6b9a-466e-95d6-ffcc761899dc.png">

**Comment by Clon1998** [comment]
I will look for a good way to add this feature. Probably by opening a dialog to enter the parameters.

**Comment by Clon1998** [comment]
Added in f6181efb25b244715bb939fe2b5c1c2e5d7330ed

**Comment by Clon1998** [comment]
Available soon in version 2.1.x
