### ISSUE TITLE
iOS features widgets

### ISSUE THREAD

**Issue by Rick88Stang** [Clon1998/mobileraker#79]
Coming from octoprint and using octopod for years I would love to see this app blossom! Is there any chance on adding a iPhone widget and Apple Watch support?

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Clon1998** [comment]
Hey,
since the app is cross platform i currently have no plans to implement widgets nor watch support.
