### ISSUE TITLE
Old Tablet Compatibility - (Cheapskate, I know)

### ISSUE THREAD

**Issue by tiaanv** [Clon1998/mobileraker#82]
**Is your feature request related to a problem? Please describe.**
I have a few 7" tablets, that have very little purpose, other than projects.  Android V5.01.  Not sure what the minimum version of Android required is, but I can't get the app from the play store on this tablet.

**Describe the solution you'd like**
Is there any chance the minimum version requirement can be reduced for old tablets, or even maybe just a "workaround" APK built?

**Describe alternatives you've considered**
I guess I could just not use the tablet...  Or purchase another tablet, but then probably a more direct PI based solution would be better with Klipper/Mainsail.

**Comment by Clon1998** [comment]
Sadly the minimum SDK version for mobileraker is 25 (Android 7.1).
That's due to libraries and external packages mobileraker uses.
