### ISSUE TITLE
Feature request: Z-Tilt

### ISSUE THREAD

**Issue by dstrelnikov** [Clon1998/mobileraker#83]
Please consider adding a `Z-TILT` button to the motion section for compatible printers.

**Comment by Clon1998** [comment]
Mhh 🧐
Which version if mobileraker are you using?
I added Z tilt, Z adjust and more in the latest version.

**Comment by dstrelnikov** [comment]
It's 2.0.1. Unfortunately I don't have a `Z-TILT` button. Please let me know if I can share some debug information to diagnose this issue.

**Comment by Clon1998** [comment]
Seems like I did a little copy-paste error while adding the `Z-Tilt btn`.
Fixed in ede2f65

**Comment by Clon1998** [comment]
New version `2.0.2` should be available now in Play+Ios Store

**Comment by dstrelnikov** [comment]
Just updated and can confirm that it indeed works now :+1:
