### ISSUE TITLE
Bed mesh button is not visible on initial screen

### ISSUE THREAD

**Issue by papazogl0** [Clon1998/mobileraker#9]
**Reproduction steps:**
1. Open mobileraker
2. Navigate to second tab
3. Navigate back to first tab

**Actual result:**
"Mesh" button is not visible in first tab on initial open, but is visible after the second tab was opened previously.

**Expected result:**
"Mesh" button is visible on first tab on initial open.

**Visual example:**
![mobileraker_mesh](https://user-images.githubusercontent.com/2265910/130143185-f8693082-34f1-444d-a59c-2245229b0e5d.gif)

**Comment by Clon1998** [comment]
Fixed in 3c88b3cacab9eb8e3cd6ebb1bda67b7294fad097
