### ISSUE TITLE
Landscape webcam view in full screen mode

### ISSUE THREAD

**Issue by Redwish89** [Clon1998/mobileraker#95]
When opening the webcam in fullscreen mode it would be more useful to have it rotated in landscape mode to take use of the mobile displays. Otherwise when zooming use the full screen instead of a frame. Switched from Octoprint on an older printer and found this a useful feature

**Comment by Clon1998** [comment]
I will add an option to configure that behavior I think.
Regarding zoom, I also would prefer that the image would use the entire space during zooming, sadly flutter currently does not support that.

**Comment by Clon1998** [comment]
Added in [2.3.0](https://github.com/Clon1998/mobileraker/releases/tag/android2.3.0)
